/* ==================================================================================
       LIFE IN THE UK: DISTINCT EXAM QUESTIONS (143 Qs)
       Includes only the unique, non-padded questions extracted from the 17 PDFs.
       All language has been expanded into full sentences with proper formatting.
================================================================================== */

window.EXAM_QUESTIONS = [
  // --- EXAM 01 ---
  [1, "Values & Principles", "What are two responsibilities that you will have as a British citizen or permanent resident?", ["To look after your family and the local environment.", "To remain living in the United Kingdom forever.", "To promote work within your local community.", "There are no specific civic responsibilities."], 0, "If you wish to be a permanent resident or citizen, you should look after yourself and your family, and look after the area in which you live.", "Respect the law and protect your local area!"],
  [2, "Geography & Identity", "Where is Big Ben located?", ["At Buckingham Palace.", "At the Tower of London.", "At Trafalgar Square.", "At the Houses of Parliament."], 3, "Big Ben is the nickname for the great bell of the clock at the Houses of Parliament in London.", "Big Ben is chiming in the House!"],
  [3, "History", "In which year were women given the right to vote at the age of 21, the same as men?", ["1918", "1903", "1928", "1923"], 2, "In 1928, women were finally given the right to vote at the age of 21, achieving voting equality with men.", "1928 is great for women's voting fate!"],
  [4, "Geography & Identity", "Where is the United Kingdom geographically located?", ["In the south-west of Europe.", "In the north-east of Europe.", "In the north-west of Europe.", "In the south-east of Europe."], 2, "The United Kingdom is located in the north-west of Europe.", "The North-West of Europe is the best!"],
  [5, "Government & Law", "How are solicitors' fees usually calculated?", ["Based on the specific nature and importance of the case.", "Based on the amount of time they spend working on the case.", "Based on a fixed fee set by the local council.", "Based on a direct order from a presiding judge."], 1, "Solicitors usually charge their clients based on how much time they spend working on a case.", "Time is money when paying solicitors!"],
  [6, "Government & Law", "By law, which two types of media must give balanced coverage of all political parties before an election?", ["The internet and national newspapers.", "National newspapers and radio broadcasts.", "Television and radio broadcasts.", "The internet and television broadcasts."], 2, "By law, radio and television coverage of the political parties must be balanced, giving equal time to rival viewpoints.", "Radio and TV must remain equal and free!"],
  [7, "Geography & Identity", "Which of the following territories is a Crown dependency but is NOT part of the United Kingdom?", ["Northern Ireland", "Wales", "The Channel Islands", "Scotland"], 2, "The Channel Islands are British overseas territories linked to the UK, but they are not part of it.", "Channel your dependency to the islands!"],
  [8, "History", "What did the British engineer Sir Frank Whittle invent in the 1930s?", ["The radar system.", "The hovercraft.", "The jet engine.", "The ballpoint pen."], 2, "The jet engine was developed in Britain in the 1930s by Sir Frank Whittle.", "Whittle down your travel time with a jet!"],
  [9, "Modern Society & Culture", "Which British poet wrote the famous poem 'The Daffodils'?", ["William Blake", "Robert Browning", "Lord Byron", "William Wordsworth"], 3, "The British poet William Wordsworth wrote the famous poem 'The Daffodils'.", "His words have worth, just like Daffodils!"],
  [10, "History", "Who was given the title of Lord Protector of England?", ["King Charles I", "King Charles II", "Sir Winston Churchill", "Oliver Cromwell"], 3, "Oliver Cromwell was given the title of Lord Protector and ruled England until his death in 1658.", "Cromwell protected the realm without a crown!"],
  [11, "Modern Society & Culture", "In the Christian calendar, what are the 40 days before Easter known as?", ["Diwali", "Lent", "Hannukah", "Vaisakhi"], 1, "The 40 days of fasting and reflection before Easter are known as Lent.", "Lent is 40 days spent preparing for Easter!"],

  // --- EXAM 02 ---
  [12, "Government & Law", "Which of the following areas is the Home Secretary responsible for?", ["Health and social care.", "National defence and the armed forces.", "Schools and national education.", "Crime, policing, and immigration."], 3, "The Home Secretary is the Cabinet minister responsible for crime, local policing, and immigration.", "Your Home is kept safe with proper policing!"],
  [13, "Geography & Identity", "St Helena is a British overseas territory and it is officially part of the United Kingdom.", ["True", "False"], 1, "False. British overseas territories, such as St Helena, are linked to the UK but are not part of it.", "St Helena is safely overseas!"],
  [14, "Government & Law", "Several senior bishops of the Church of England are permitted to sit in the House of Lords.", ["True", "False"], 0, "True. Several senior bishops of the Church of England are appointed to sit in the House of Lords.", "The Bishops sit peacefully with the Lords!"],
  [15, "Government & Law", "When walking your dog in a public place, what must you ensure by law?", ["That your dog does not play with other dogs.", "That your dog wears a collar showing the name and address of the owner.", "That your dog wears a high-visibility jacket.", "That your dog does not bark loudly."], 1, "By law, all dogs in public places must wear a collar showing the name and address of the owner.", "Collar up your pup with an address!"],
  [16, "History", "Women over the age of 30 were given the right to vote in 1918 in recognition of their contribution to which war?", ["The Second World War", "The Crimean War", "The First World War", "The English Civil War"], 2, "In 1918, women over 30 were given voting rights, partly in recognition of the contribution they made during the First World War.", "The First World War won women the vote!"],
  [17, "History", "Which conflict was the last successful foreign invasion of England, taking place in 1066?", ["The Viking invasion", "The Anglo-Saxon Conquest", "The Roman invasion", "The Norman Conquest"], 3, "The Norman Conquest of 1066 was the last successful foreign invasion of England.", "The Normans knocked last in 1066!"],
  [18, "Geography & Identity", "Where are the official Crown Jewels kept?", ["At the House of Commons", "At the Tower of London", "At Buckingham Palace", "At Windsor Castle"], 1, "The historic Crown Jewels are kept securely at the Tower of London.", "The shiny jewels are locked in the Tower!"],
  [19, "Modern Society & Culture", "Which modern sport can be traced back to 15th-century Scotland?", ["Golf", "Tennis", "Football", "Rugby"], 0, "The modern game of golf can be traced back to 15th-century Scotland.", "Golfing originated in the Scottish Highlands!"],
  [20, "History", "Who was the first person in England to print books using a mechanical printing press?", ["William Shakespeare", "John Barbour", "Geoffrey Chaucer", "William Caxton"], 3, "William Caxton was the first person in England to print books using a printing press.", "Caxton printed a ton of new books!"],
  [21, "Government & Law", "Which court deals with the majority of minor criminal cases in England and Wales?", ["The High Court", "The Justice of the Peace Court", "The Magistrates' Court", "The Crown Court"], 2, "In England and Wales, most minor criminal cases are dealt with in a Magistrates' Court.", "Magistrates handle the minor legal matters!"],
  [22, "History", "What did the Scottish engineer John Logie Baird successfully develop in the 1920s?", ["The mechanical television.", "The radar system.", "The personal computer.", "The radio broadcast system."], 0, "The first working television system was developed by the Scotsman John Logie Baird in the 1920s.", "Baird broadcasted the first moving TV images!"],

  // --- EXAM 03 ---
  [23, "Values & Principles", "Which of the following concepts is considered a fundamental principle of British life?", ["Communism", "Intolerance of different faiths", "Individual liberty", "Social inequity"], 2, "Individual liberty is explicitly listed as a fundamental principle of British life in the official guide.", "Individual liberty is guaranteed for all!"],
  [24, "Modern Society & Culture", "Wales has its own established, official state church.", ["True", "False"], 1, "False. There is no officially established state Church in Wales or Northern Ireland.", "There is no state church ruling in Wales!"],
  [25, "Modern Society & Culture", "What is the traditional Scottish name for New Year's Eve?", ["Vaisakhi", "Hannukah", "Diwali", "Hogmanay"], 3, "In Scotland, the 31st of December is traditionally called Hogmanay.", "Celebrate Hogmanay for the new day!"],
  [26, "History", "Why did King Henry VIII establish the Church of England?", ["Because he wanted to introduce Protestantism to the country.", "Because the Pope refused to grant him a divorce from Catherine of Aragon.", "Because he wanted to legally unite England and Scotland.", "Because he was forced to by a popular peasant rebellion."], 1, "Henry VIII established the Church of England because the Pope refused to approve his divorce from his first wife.", "Henry started a church just to get a divorce!"],
  [27, "History", "What is the name of the long war that English kings fought against France during the Middle Ages?", ["The Crimean War", "The First World War", "The Hundred Years War", "The Boer War"], 2, "English kings fought a long war with France known as the Hundred Years War.", "They fought France for over a hundred years!"],
  [28, "History", "Why did the British government anger the American colonies, leading to the American War of Independence?", ["Because the British wanted to enforce a new king upon them.", "Because the British government attempted to tax the colonies without their representation.", "Because there were not enough local jobs provided by the British.", "Because the British tried to restrict their religious freedom."], 1, "The British government angered the American colonies by insisting they pay taxes despite having no representation in Parliament.", "No new taxes without a voice!"],
  [29, "History", "During which historical period did the Black Death arrive in Britain?", ["The Golden Age", "The Stone Age", "The Middle Ages", "The Iron Age"], 2, "The Black Death came to Britain in 1348, which was during the Middle Ages.", "The Black Death struck during the Middle Ages!"],
  [30, "History", "Who was the founder and leader of the suffragettes, the group that campaigned for women's right to vote?", ["Queen Victoria", "Oliver Cromwell", "Florence Nightingale", "Emmeline Pankhurst"], 3, "Emmeline Pankhurst was the prominent leader of the suffragettes.", "Pankhurst pushed hard for the female vote!"],
  [31, "Geography & Identity", "Cardiff is the capital city of which constituent country of the UK?", ["Scotland", "Northern Ireland", "Ireland", "Wales"], 3, "The capital city of Wales is Cardiff.", "Cardiff is the capital for the Welsh!"],
  [32, "History", "During the Great Depression in the 1930s, which major industry was particularly badly affected?", ["Housing construction", "Heavy shipbuilding", "Automobile manufacturing", "Commercial aviation"], 1, "During the Great Depression, traditional heavy industries such as shipbuilding were severely affected.", "The massive ships stopped building in the 30s!"],
  [33, "Modern Society & Culture", "Who was the first man in the world to run one mile in under four minutes?", ["Sir Chris Hoy", "Sir Roger Bannister", "David Weir", "Mo Farah"], 1, "Sir Roger Bannister was the first man in the world to run a mile in under four minutes in 1954.", "Bannister ran the fastest mile!"],
  [34, "Modern Society & Culture", "Which festival is celebrated by Muslims to mark the end of Ramadan?", ["Hannukah", "Vaisakhi", "Eid ul Adha", "Eid al-Fitr"], 3, "Eid al-Fitr celebrates the end of the fasting month of Ramadan.", "Fitr officially finishes the fast!"],

  // --- EXAM 04 ---
  [35, "History", "Which historic 1815 battle marked the final conflict between Great Britain and France?", ["The Battle of Trafalgar", "The Battle of Waterloo", "The Battle of Hastings", "The Battle of Agincourt"], 1, "In 1815, the French Wars ended when the Duke of Wellington defeated Emperor Napoleon at the Battle of Waterloo.", "Waterloo permanently ended the French wars!"],
  [36, "Geography & Identity", "Which spring flower is strongly associated with Wales?", ["The Daffodil", "The Rose", "The Shamrock", "The Thistle"], 0, "The flower officially associated with Wales is the daffodil.", "Yellow daffodils bloom for Wales!"],
  [37, "History", "During the reign of King Charles II, what major event caused massive destruction throughout the city of London?", ["A European war", "A massive flood", "A great fire", "An earthquake"], 2, "During Charles II's reign, the Great Fire of 1666 destroyed much of the city, including St Paul's Cathedral.", "A Great Fire spread in 1666!"],
  [38, "Government & Law", "What is the maximum amount of time allowed between general elections in the UK?", ["Every 3 years", "Every 4 years", "Every 5 years", "Every 10 years"], 2, "Members of Parliament are elected at a General Election, which must be held at least every five years.", "You must vote at least every 5 years!"],
  [39, "Geography & Identity", "Scotland produces its own banknotes, which are legally valid for use everywhere in the UK.", ["True", "False"], 0, "True. Scottish banknotes are legally valid and can be used across the entire UK.", "Scottish notes work anywhere in the UK!"],
  [40, "Government & Law", "Which prominent charity works specifically to preserve important buildings, coastlines, and the countryside?", ["Shelter", "Age UK", "Crisis", "The National Trust"], 3, "The National Trust works to preserve important heritage sites and countryside.", "Trust them to protect the old buildings!"],
  [41, "Modern Society & Culture", "What famous comedic character was played by the British actor Charlie Chaplin?", ["A superhero", "A tramp", "A scientific genius", "A bandit"], 1, "Sir Charlie Chaplin became world-famous in silent movies for playing his iconic 'tramp' character.", "Chaplin was famously dressed as a tramp!"],
  [42, "Government & Law", "You must be at least 21 years old to stand as a Member of Parliament (MP).", ["True", "False"], 1, "False. Anyone aged 18 or over can legally stand for election as an MP.", "You only need to be 18 to stand for MP!"],
  [43, "History", "Who successfully developed the radar system?", ["John Logie Baird", "Sir Frank Whittle", "Sir Christopher Cockerell", "Sir Robert Watson-Watt"], 3, "Sir Robert Watson-Watt developed the radar system, which was vital during World War II.", "Watson-Watt kept a close watch on the radar!"],
  [44, "Government & Law", "What is the address of the official home of the British Prime Minister?", ["18 Oxford Street", "Buckingham Palace", "Windsor Castle", "10 Downing Street"], 3, "The official residence of the Prime Minister is 10 Downing Street in London.", "Number 10 is reserved for the PM!"],

  // --- EXAM 05 ---
  [45, "Modern Society & Culture", "During which months of the year does the Christian festival of Easter usually take place?", ["November or December", "January or February", "March or April", "May or June"], 2, "Easter is a spring festival that takes place in March or April.", "Easter happens during the Spring!"],
  [46, "Geography & Identity", "Which of the following is NOT a valid coin in the UK currency system?", ["The 1p coin", "The 5p coin", "The 25p coin", "The £1 coin"], 2, "There is no 25p coin in the UK currency system.", "There are no quarter coins in the UK!"],
  [47, "Geography & Identity", "Where is the famous ecological attraction known as the Eden Project located?", ["Dorset", "Cornwall", "Devon", "Somerset"], 1, "The Eden Project, known for its massive biomes, is located in Cornwall.", "The Eden Project blossoms in Cornwall!"],
  [48, "Government & Law", "What kind of charitable organisation is 'Friends of the Earth'?", ["An environmental charity.", "A medical research charity.", "A charity working with pets.", "A charity working with older people."], 0, "Friends of the Earth is a prominent environmental charity.", "Friends of the Earth naturally protect nature!"],
  [49, "Government & Law", "If a husband forces his wife to have sex, he can be legally charged with rape.", ["True", "False"], 0, "True. Rape within a marriage is a serious criminal offence.", "Consent is a strict legal requirement!"],
  [50, "History", "In which country did the Boer War (1899-1902) take place?", ["The Netherlands", "The Falkland Islands", "Gibraltar", "South Africa"], 3, "The Boer War took place in South Africa, fighting against Dutch settlers.", "The Boers fought the British in South Africa!"],
  [51, "Government & Law", "In British politics, what does the term 'canvassing' refer to?", ["Donating blood to help people.", "Volunteering for an environmental charity.", "Caring for animals at a local rescue shelter.", "Persuading people to vote for a political party."], 3, "Canvassing involves political members knocking on doors or handing out leaflets to persuade people to vote for them.", "Canvassing is another word for political campaigning!"],
  [52, "Modern Society & Culture", "Which novel, written by J.R.R. Tolkien, was voted the country's best-loved novel in a 2003 poll?", ["Oliver Twist", "James Bond", "Pride and Prejudice", "The Lord of the Rings"], 3, "In 2003, The Lord of the Rings was voted the country's best-loved novel.", "Tolkien's magical ring is the best loved!"],
  [53, "History", "In which year did Germany invade Poland, prompting the start of the Second World War?", ["1942", "1941", "1940", "1939"], 3, "The Second World War started when Adolf Hitler invaded Poland in 1939.", "1939 officially started the conflict line!"],

  // --- EXAM 06 ---
  [54, "History", "Which ancient people made the very first coins to be minted in Britain?", ["The people of the Stone Age", "The Anglo-Saxons", "The people of the Iron Age", "The Romans"], 2, "The people of the Iron Age made the first coins, marking the beginnings of recorded British history.", "The first coins were minted in the Iron Age!"],
  [55, "Geography & Identity", "Which historical figure ordered the construction of the Tower of London?", ["William the Conqueror", "Queen Victoria", "Queen Elizabeth I", "Oliver Cromwell"], 0, "William the Conqueror built the White Tower at the Tower of London to establish his authority.", "William the Conqueror built the mighty Tower!"],
  [56, "Geography & Identity", "There are 15 national parks across England, Wales, and Scotland. What exactly are national parks?", ["Giant agricultural greenhouses.", "Land formations made entirely of volcanic lava.", "Areas of strictly protected countryside.", "Preserved medieval buildings."], 2, "National Parks are large areas of protected countryside where development is strictly controlled.", "National Parks exist to protect the countryside!"],
  [57, "History", "What was the name of the massive survey of land and property commissioned by William the Conqueror in 1086?", ["The Magna Carta", "The Domesday Book", "The Bayeux Tapestry", "The Canterbury Tales"], 1, "The Domesday Book was a comprehensive survey of all land and property in England.", "The Domesday Book counted every single farm!"],
  [58, "History", "Why did the British government delay the implementation of 'Home Rule' for Ireland in 1914?", ["Because of the outbreak of the First World War.", "Because of the outbreak of the Second World War.", "Because there was no king on the British throne at the time.", "Because of the outbreak of the Black Death."], 0, "The outbreak of the First World War led the British government to postpone the changes in Ireland.", "The First World War delayed the Home Rule promise!"],
  [59, "History", "Which of the following statements about Queen Elizabeth I is true?", ["She was a Protestant who succeeded in finding a balance between Catholics and extreme Protestants.", "She was a Catholic who sought to forcefully convert all extreme Protestants.", "She was a devout Muslim who built new religious temples.", "She was a staunch atheist who banned the Church of England."], 0, "Elizabeth I was a Protestant who successfully balanced the views of Catholics and extreme Protestants.", "Elizabeth successfully balanced the religious divide!"],
  [60, "Government & Law", "Which two types of documents do you need to successfully apply for a National Insurance number?", ["A document proving your identity and a document proving you have permission to work in the UK.", "A tenancy agreement and a recent utility bill.", "A signed contract from your employer and a university degree.", "A valid library card and a document proving your identity."], 0, "To apply, you need documents that prove your identity and that you have legal permission to work in the UK.", "You must prove your identity and your right to work!"],

  // --- EXAM 07 ---
  [61, "Modern Society & Culture", "On what date is the festival of Halloween celebrated?", ["The 5th of November", "The 11th of November", "The 31st of October", "The 1st of April"], 2, "Halloween is traditionally celebrated every year on the 31st of October.", "Prepare for a spooky 31st of October!"],
  [62, "History", "The historic Bill of Rights in 1689 officially gave women the right to vote in general elections.", ["True", "False"], 1, "False. The Bill of Rights of 1689 limited the king's power and confirmed the rights of Parliament, but it did not give women the vote.", "The Bill of Rights limited the King, not voting laws!"],
  [63, "Modern Society & Culture", "What is the name of the most famous cricket competition played regularly between England and Australia?", ["The Ashes", "The Six Nations Championship", "The Grand National", "The Australian Open"], 0, "The Ashes is a famous series of Test cricket matches played exclusively between England and Australia.", "They burn the cricket stumps down to Ashes!"],
  [64, "History", "What was the biggest source of employment in Britain during the 18th century?", ["Commercial fishing", "Academic teaching", "The aircraft industry", "Manufacturing and agriculture"], 3, "During the 18th century, the biggest source of employment was manufacturing alongside traditional agriculture.", "People were busy making things in the 18th century!"],
  [65, "History", "What was the name of the movement of opinion against the authority of the Pope during the reign of King Henry VIII?", ["The Spanish Inquisition", "The Holy Wars", "The Reformation", "The Enlightenment"], 2, "The Reformation was a major movement that challenged the authority of the Pope and the Catholic Church.", "Henry VIII started reforming the English church!"],
  [66, "Government & Law", "If you need a National Insurance Number, which government department must you contact?", ["The National Health Service (NHS).", "The Department for Work and Pensions (DWP).", "Your local Member of Parliament (MP).", "Your current employer's human resources team."], 1, "You must telephone the Department for Work and Pensions (DWP) to arrange to get a National Insurance number.", "The DWP handles your work and pensions!"],
  [67, "Modern Society & Culture", "Which of the following is a major, multi-day horse-racing event held in England?", ["The Wimbledon Championship", "Royal Ascot", "The Open Championship", "The Six Nations Championship"], 1, "Royal Ascot is a famous five-day horse-racing meeting in Berkshire, frequently attended by the Royal Family.", "Ascot is the royal destination for horse racing!"],
  [68, "Government & Law", "In the Scottish legal system, how many members form a standard criminal jury?", ["12 members", "14 members", "15 members", "20 members"], 2, "In Scotland, a criminal jury is uniquely made up of 15 members, unlike the 12 used in England.", "There are 15 kilts sitting on a Scottish jury!"],

  // --- EXAM 08 ---
  [69, "Geography & Identity", "Which wild plant is the national flower associated with Scotland?", ["The Shamrock", "The Rose", "The Daffodil", "The Thistle"], 3, "The thistle is the prickly flower officially associated with Scotland.", "The prickly purple thistle represents the Highlands!"],
  [70, "Government & Law", "Complaints against the police can only be made by writing directly to the Chief Constable of the police force involved.", ["True", "False"], 1, "False. Complaints can also be made to an independent body, such as the Independent Office for Police Conduct.", "Independent police complaint bodies exist!"],
  [71, "Modern Society & Culture", "On what date is St David's Day, the national day of Wales, celebrated?", ["The 1st of March", "The 17th of March", "The 23rd of April", "The 30th of November"], 0, "St David's Day is celebrated annually on the 1st of March.", "St David marches first into the calendar!"],

  // --- EXAM 09 ---
  [72, "Geography & Identity", "Which small green plant is associated as the national symbol of Northern Ireland?", ["The Daffodil", "The Thistle", "The Shamrock", "The Rose"], 2, "The shamrock is the traditional green plant associated with Northern Ireland.", "The lucky green Shamrock is for Northern Ireland!"],
  [73, "Modern Society & Culture", "The £100 note is the highest value banknote currently in general circulation in the UK.", ["True", "False"], 1, "False. The highest value note in general circulation printed by the Bank of England is the £50 note.", "Fifty pounds is the top note in your wallet!"],
  [74, "Geography & Identity", "In which constituent country of the UK is the Lake District National Park located?", ["Scotland", "Wales", "England", "Northern Ireland"], 2, "The Lake District is England's largest National Park.", "The beautiful Lakes are located in England!"],
  [75, "Modern Society & Culture", "Which legendary British playwright was born in the town of Stratford-upon-Avon?", ["Jane Austen", "Charles Dickens", "William Shakespeare", "Thomas Hardy"], 2, "William Shakespeare was born in Stratford-upon-Avon in 1564.", "Shakespeare wrote his plays in Stratford!"],
  [76, "History", "What massive social change did the Education Act 1944 (also known as the Butler Act) introduce?", ["Free university education for all citizens.", "Free primary education across the entire British Empire.", "Free secondary education in England and Wales.", "Paid private schooling for urban workers."], 2, "The Education Act 1944 introduced free secondary education for all children in England and Wales.", "Mr Butler served up free secondary schools!"],
  [77, "Government & Law", "What is the purpose of the 'small claims procedure' in the legal system?", ["It is an informal way of settling minor financial disputes without spending a lot of money on lawyers.", "It is a procedure to help people make small home insurance claims after a burglary.", "It is a special court designed to handle serious corporate fraud.", "It is a fast-track court specifically for handling family divorces."], 0, "The small claims procedure allows people to easily settle minor civil and financial disputes informally.", "Small claims court handles minor financial disputes!"],
  [78, "History", "Which magnificent building was constructed in Hyde Park to host the Great Exhibition of 1851?", ["The Crystal Palace", "Buckingham Palace", "Kensington Palace", "Apsley House"], 0, "The Crystal Palace, a huge building made of steel and glass, was built for the Great Exhibition.", "A massive glass Crystal Palace was built for the exhibition!"],
  [79, "History", "Who was Florence Nightingale?", ["She was a pioneering economist.", "She was a landscape painter.", "She was the founder of modern nursing.", "She was a Victorian poet."], 2, "Florence Nightingale was a famous nurse who is widely regarded as the founder of modern professional nursing.", "Nightingale was the lady with the nursing lamp!"],

  // --- EXAM 10 ---
  [80, "Modern Society & Culture", "Who is the officially recognised patron saint of England?", ["St George", "St Patrick", "St David", "St Andrew"], 0, "The patron saint of England is St George.", "St George slays the dragon for England!"],
  [81, "Geography & Identity", "Where is the famous Loch Lomond and the Trossachs National Park located?", ["In England", "In Wales", "In Scotland", "In Northern Ireland"], 2, "Loch Lomond and the Trossachs National Park is a beautiful area located in the west of Scotland.", "Loch Lomond is a famous Scottish loch!"],
  [82, "Modern Society & Culture", "Which famous collection of stories is associated with the 14th-century author Geoffrey Chaucer?", ["The Cambridge Tales", "The Eastbourne Tales", "The Canterbury Tales", "The London Tales"], 2, "Geoffrey Chaucer wrote a famous collection of poetic stories known as The Canterbury Tales.", "Chaucer wrote the classic Canterbury Tales!"],
  [83, "Modern Society & Culture", "On what date is the public holiday known as Boxing Day celebrated?", ["The 31st of October", "The 26th of December", "The 24th of December", "The 1st of January"], 1, "Boxing Day is the day immediately after Christmas Day, falling on the 26th of December.", "Box up your gifts on the 26th of December!"],
  [84, "Modern Society & Culture", "What is the official term for public holidays when banks and many other businesses close for the day?", ["Credit Holidays", "Branch Holidays", "Bank Holidays", "Business Holidays"], 2, "Public holidays in the UK are commonly referred to as Bank Holidays.", "The banks close their doors on Bank Holidays!"],
  [85, "Modern Society & Culture", "What major scientific discovery is Sir Isaac Newton most famous for?", ["The discovery of insulin.", "The discovery of gravity.", "The discovery of penicillin.", "The discovery of steam power."], 1, "Sir Isaac Newton is most famous for his published mathematical principles regarding how gravity applies to the universe.", "Newton figured out gravity from a falling apple!"],
  [86, "History", "In what year did the First World War officially come to an end?", ["In 1922", "In 1918", "In 1945", "In 1943"], 1, "The First World War officially ended on the 11th of November 1918.", "The First World War ended in 1918!"],
  [87, "History", "Which Roman Emperor built a massive wall across the north of England to keep out the Picts?", ["Queen Boudicca", "Emperor Hadrian", "Emperor Claudius", "Julius Caesar"], 1, "Emperor Hadrian built a wall in the north of England to keep out the ancestors of the Scottish people.", "Hadrian built Hadrian's Wall!"],
  [88, "Modern Society & Culture", "Which two elite universities participate in an annual competitive rowing race on the River Thames?", ["The University of Oxford and the University of Cambridge.", "The University of Manchester and the University of Warwick.", "The University of London and the University of York.", "The University of Edinburgh and the University of St Andrews."], 0, "There is a highly popular yearly rowing race on the Thames between the universities of Oxford and Cambridge.", "Oxford and Cambridge row it out on the Thames!"],
  [89, "Government & Law", "Does the United Kingdom have a single, formal written constitution?", ["Yes, it is written in a single document.", "No, it is entirely unwritten and uncodified."], 1, "No, the British constitution is not written down in any single document; it is a collection of laws and conventions.", "The UK is famous for its unwritten rules!"],

  // --- EXAM 11 ---
  [90, "Geography & Identity", "Which specific area of London is world-famous for its concentration of historic venues and is known as 'Theatreland'?", ["The Docklands", "London's East End", "London's West End", "London's South End"], 2, "London's West End is famously known as 'Theatreland' due to its numerous theatres.", "The West End is where the best shows are!"],
  [91, "Geography & Identity", "What is the official name of the currency used in the United Kingdom?", ["The Euro", "The Pound Sterling", "The Peso", "The Dollar"], 1, "The official currency of the UK is the Pound Sterling.", "The UK trades in the Pound Sterling!"],
  [92, "Modern Society & Culture", "What descriptive name is frequently given to the Hindu and Sikh festival of Diwali?", ["The Festival of Lights", "Ash Wednesday", "Good Friday", "Easter Monday"], 0, "Diwali is widely celebrated and is often called the Festival of Lights.", "Diwali delights the streets with bright lights!"],
  [93, "History", "During the 18th century, what was the 'Enlightenment'?", ["A period of total peace and zero warfare in England.", "A period when radical new ideas about politics, philosophy, and science were developed.", "A period when England became the largest empire the world had ever seen.", "A period of rapid economic recovery immediately following a world war."], 1, "The Enlightenment was a period of immense intellectual growth and scientific discovery during the 18th century.", "People became 'enlightened' with brilliant new ideas!"],
  [94, "History", "Which famous architect was commissioned to rebuild St Paul's Cathedral after the Great Fire of London in 1666?", ["Robert Adam", "Sir Christopher Wren", "Sir Norman Foster", "Dame Zaha Hadid"], 1, "Sir Christopher Wren was the brilliant architect who designed the new St Paul's Cathedral.", "Wren rebuilt the cathedral for the men of London!"],
  [95, "History", "Against which country did Britain fight alongside Turkey and France during the Crimean War?", ["Turkey", "Russia", "France", "Germany"], 1, "From 1853 to 1856, Britain fought alongside Turkey and France against Russia in the Crimean War.", "The Crimean War was a united front against Russia!"],
  [96, "Government & Law", "How old do you legally have to be to buy alcohol in a pub or shop in the UK?", ["17 years old", "18 years old", "19 years old", "20 years old"], 1, "It is a criminal offence to sell alcohol to anyone who is under 18 years old.", "You unlock the right to a pint at 18!"],

  // --- EXAM 12 ---
  [97, "Modern Society & Culture", "Is the British Broadcasting Corporation (BBC) officially controlled by the UK government?", ["Yes, it is a branch of the government.", "No, it is fully independent of the government."], 1, "No. The BBC is the largest broadcaster in the world and is strictly independent of the government.", "The BBC maintains strict political independence!"],
  [98, "Government & Law", "How many elected members serve in the Northern Ireland Assembly?", ["12 members", "60 members", "90 members", "108 members"], 2, "The Northern Ireland Assembly currently consists of exactly 90 elected members, known as MLAs.", "There are exactly 90 seats in the NI Assembly!"],
  [99, "History", "Who was in command of the British naval fleet during the decisive Battle of Trafalgar?", ["Oliver Cromwell", "The Duke of Wellington", "Robert the Bruce", "Admiral Horatio Nelson"], 3, "Admiral Horatio Nelson was in charge of the British fleet at Trafalgar, where he was tragically killed in action.", "Admiral Nelson conquered the sea!"],
  [100, "Modern Society & Culture", "Which major international sporting event was hosted by the UK in London in the year 2012?", ["The FIFA World Cup", "The Rugby World Cup", "The Olympic Games", "The Eurocup Basketball tournament"], 2, "The UK proudly hosted the Olympic and Paralympic Games in London in 2012.", "London shone brightly during the 2012 Olympics!"],
  [101, "History", "Because King Charles I believed in the 'Divine Right of Kings', what reckless political action did he attempt to take?", ["He attempted to rule the country entirely without Parliament.", "He attempted to rule only with the direct approval of Parliament.", "He attempted to raise vast amounts of money for Parliament.", "He attempted to violently restore Catholicism in Britain."], 0, "Charles I believed the king was appointed directly by God, and he controversially tried to rule without Parliament.", "Charles ignored Parliament entirely!"],
  [102, "Geography & Identity", "What does the term 'Union Jack' refer to?", ["The official flag of the Commonwealth of Nations.", "The official national flag of the United Kingdom.", "The protective shield used by medieval British knights.", "A prominent trade union protecting workers' rights."], 1, "The Union Flag, which is the official flag of the United Kingdom, is commonly known as the Union Jack.", "The Union Jack flies high over the UK!"],
  [103, "History", "Who was voted the 'Greatest Briton of all time' by the public in a massive 2002 BBC poll?", ["Mo Farah", "Admiral Horatio Nelson", "Sir Winston Churchill", "Clement Attlee"], 2, "In 2002, Sir Winston Churchill was voted the greatest Briton of all time for his extraordinary wartime leadership.", "Churchill was universally voted the Greatest!"],
  [104, "Modern Society & Culture", "Approximately what proportion of the modern UK workforce is made up of women?", ["About half of the workforce.", "About a quarter of the workforce.", "About a third of the workforce.", "About ten percent of the workforce."], 0, "Women in Britain today have equal workplace rights and make up about half of the entire workforce.", "Women make up fully half of the workforce!"],

  // --- EXAM 13 ---
  [105, "Modern Society & Culture", "On what exact date is St George's Day, the patron saint's day of England, celebrated?", ["The 17th of March", "The 30th of November", "The 1st of March", "The 23rd of April"], 3, "St George's Day is celebrated annually on the 23rd of April.", "St George slays the dragon on the 23rd of April!"],
  [106, "Geography & Identity", "Which of the following is officially the largest National Park in England?", ["Snowdonia National Park", "Loch Lomond and the Trossachs", "The Giant's Causeway", "The Lake District"], 3, "Covering a vast area in the north-west, the Lake District is England's largest national park.", "The Lake District is undeniably the biggest!"],
  [107, "History", "Boudicca was a fierce tribal queen who led an uprising against which foreign invaders?", ["The Normans", "The Vikings", "The Anglo-Saxons", "The Romans"], 3, "Boudicca was the queen of the Iceni tribe who famously led a bloody rebellion against the occupying Romans.", "Boudicca bravely fought the mighty Romans!"],
  [108, "Modern Society & Culture", "Which of the following statements is true regarding standard shopping hours in the UK?", ["Most shops in the UK are open seven days a week.", "All shops are legally closed on Sundays.", "Shops are only allowed to open five days a week.", "Shops are never open on public bank holidays."], 0, "Most shops in the UK are open seven days a week, although Sunday trading hours are generally shorter.", "You can hit the shops 7 days a week!"],
  [109, "History", "Which hostile country sent a massive fleet of ships, known as the Armada, to conquer England in 1588?", ["France", "Germany", "Spain", "Italy"], 2, "Spain sent the Spanish Armada in 1588 in a failed attempt to conquer England and restore Catholicism.", "The Spanish Armada sailed in 1588!"],
  [110, "Modern Society & Culture", "In which English town is the official National Horseracing Museum located?", ["Edinburgh, Scotland", "Newmarket, Suffolk", "St Andrews, Scotland", "Aintree, near Liverpool"], 1, "The National Horseracing Museum is situated in Newmarket, Suffolk.", "Newmarket is the legendary home for horses!"],
  [111, "Geography & Identity", "Which of the following historic castles is located within Scotland?", ["Crathes Castle", "Caernarfon Castle", "Bodiam Castle", "Powis Castle"], 0, "Crathes Castle is a beautifully preserved 16th-century tower house located in Aberdeenshire, Scotland.", "Crathes Castle stands tall in Scotland!"],
  [112, "Modern Society & Culture", "Who was a famous and highly influential Art Deco ceramic designer during the 20th century?", ["Alexander McQueen", "Thomas Chippendale", "Clarice Cliff", "Mary Quant"], 2, "Clarice Cliff was a groundbreaking ceramic designer famous for her vibrant, geometric Art Deco pottery.", "Clarice's Ceramics were incredibly colourful!"],

  // --- EXAM 14 ---
  [113, "Modern Society & Culture", "On what date is St Patrick's Day, the patron saint's day of Northern Ireland, celebrated?", ["The 23rd of April", "The 30th of November", "The 1st of April", "The 17th of March"], 3, "St Patrick's Day is celebrated globally on the 17th of March.", "St Patrick proudly marches on the 17th!"],
  [114, "Government & Law", "How are the members of the Northern Ireland Assembly (MLAs) elected?", ["By a system of proportional representation.", "By using a system of ranked voting.", "By using the first-past-the-post system.", "By using a runoff voting system."], 0, "The Northern Ireland Assembly uses a system of proportional representation (the Single Transferable Vote).", "Proportional representation keeps NI fair!"],
  [115, "History", "Who was officially recognised as the very first Prime Minister of Great Britain?", ["Sir Winston Churchill", "The Earl of Wilmington", "Henry Pelham", "Sir Robert Walpole"], 3, "Sir Robert Walpole served as the first Prime Minister from 1721 to 1742.", "Walpole was the very first PM to hold the role!"],
  [116, "Modern Society & Culture", "Which of the following highly acclaimed British actresses has NOT won an Academy Award (Oscar)?", ["Tilda Swinton", "Emily Watson", "Dame Judi Dench", "Kate Winslet"], 1, "While many British actors have won Oscars, Emily Watson has been nominated but has not yet won.", "Emily Watson is still waiting for her Oscar!"],
  [117, "History", "What was the primary reason canals were built extensively during the Industrial Revolution?", ["To link emerging factories directly to towns, cities, and coastal ports.", "To make space for the massive fleet of new British naval ships.", "To vastly increase the number of water mills operating in the UK.", "To increase the supply of drinking water in rapidly growing towns."], 0, "Canals were built to easily and cheaply transport heavy industrial goods from factories to major ports.", "Canals were the transport highways for factories!"],
  [118, "Government & Law", "Are UK civil servants politically appointed by the ruling government?", ["Yes, they are chosen entirely by the ruling political party.", "No, they are chosen purely on merit and remain politically neutral."], 1, "No. Civil servants are not political appointees; they are strictly neutral and chosen based on merit.", "Civil servants operate on merit, not politics!"],
  [119, "History", "Which neighbouring European country partnered with Britain to successfully develop the Concorde airliner?", ["Germany", "Norway", "Italy", "France"], 3, "Britain and France jointly developed Concorde, the world's only supersonic commercial airliner.", "France and Britain connected to build Concorde!"],
  [120, "History", "Which crucial technological development was the primary driver of the rapid Industrial Revolution in Britain?", ["Magnetic Resonance Imaging (MRI).", "The application of steam power.", "The military radar system.", "The commercial hovercraft."], 1, "The development of heavy machinery and the widespread use of steam power triggered the Industrial Revolution.", "Steam powered the mighty new factories!"],

  // --- EXAM 15 ---
  [121, "History", "Following the Norman Conquest, which two distinct languages were spoken across England during the Middle Ages?", ["Welsh and Latin.", "Gaelic and Scottish.", "Norman French and Anglo-Saxon.", "Celtic and Roman."], 2, "The king and his noblemen spoke Norman French, while the peasants continued to speak Anglo-Saxon.", "French for the nobles, Saxon for the peasants!"],
  [122, "History", "In 1776, which group of British colonies famously declared their independence over the issue of taxation?", ["The North African colonies.", "The Asian colonies.", "The North American colonies.", "The South African colonies."], 2, "In 1776, the 13 North American colonies declared independence from British rule.", "America declared its independence in 1776!"],
  [123, "History", "During which period was England briefly ruled as a republic, known as the Commonwealth, rather than by a monarch?", ["Following the death of Queen Elizabeth I.", "After King Charles I was tried and executed.", "Immediately after the signing of the Magna Carta.", "Following the death of King Harold at Hastings."], 1, "When King Charles I was executed in 1649, England declared itself a republic without a monarch.", "There was absolutely no King after Charles fell!"],
  [124, "Modern Society & Culture", "Which fantasy film franchise, produced in the UK, is one of the highest-grossing cinematic franchises of all time?", ["The Harry Potter series.", "The Spider-Man series.", "The Lord of the Rings series.", "The Indiana Jones series."], 0, "The Harry Potter and James Bond films are two of the most commercially successful franchises produced in the UK.", "Harry Potter is a magical box office hit!"],
  [125, "Government & Law", "In the UK, what is the absolute minimum legal age required to drive a car or a motorcycle?", ["16 years old.", "17 years old.", "18 years old.", "21 years old."], 1, "You must be at least 17 years old to hold a licence to drive a car or motorcycle on public roads.", "You must wait until you are 17 for a motorcycle!"],
  [126, "Government & Law", "The members of the House of Lords, known as peers, are democratically elected by the British public.", ["True", "False"], 1, "False. The members of the House of Lords are appointed by the Monarch on the advice of the Prime Minister, not elected.", "Peers are appointed, never elected!"],
  [127, "History", "In which year did the historic Emancipation Act finally abolish slavery throughout the vast majority of the British Empire?", ["1835", "1823", "1807", "1833"], 3, "In 1833, the Emancipation Act definitively abolished slavery throughout the British Empire.", "The two 3s in 1833 look like broken handcuffs!"],
  [128, "Modern Society & Culture", "What genre of film are the famous 'Wallace and Gromit' movies, created by Nick Park?", ["They are dramatic soap operas.", "They are black-and-white silent movies.", "They are stop-motion animated films.", "They are high-octane action films."], 2, "Nick Park won Oscars for his highly creative stop-motion animated films featuring Wallace and Gromit.", "Wallace and Gromit are brilliant animated clay!"],
  [129, "Government & Law", "Anyone who is physically violent towards their partner—whether married or simply living together—can be criminally prosecuted.", ["True", "False"], 0, "True. Domestic violence is a severe criminal offence in the UK, regardless of marital status or gender.", "Domestic violence is strictly illegal!"],

  // --- EXAM 16 ---
  [130, "Government & Law", "When was the United Nations (UN) officially established to prevent war and promote peace?", ["Immediately after the First World War.", "Immediately after the Second World War.", "Decades before the First World War.", "In the years between the First and Second World Wars."], 1, "The UN was set up globally after the devastating conclusion of the Second World War.", "The UN was born from the ashes of WWII!"],
  [131, "Geography & Identity", "Where is the famous natural landmark known as the Giant's Causeway located?", ["In Scotland.", "In England.", "In Wales.", "In Northern Ireland."], 3, "The Giant's Causeway is a spectacular volcanic land formation located on the coast of Northern Ireland.", "Legendary giants walked on the Causeway in NI!"],
  [132, "History", "What was the ultimate fate of Mary, Queen of Scots, after she was imprisoned for 20 years by her cousin Queen Elizabeth I?", ["She married an English nobleman.", "She was exiled safely to France.", "She was tried and executed for treason.", "She was peacefully returned to Scotland."], 2, "Mary was eventually executed because she was accused of plotting to overthrow Elizabeth I.", "Mary tragically lost her head to the executioner!"],
  [133, "History", "Which of the following tribes invaded Britain from northern Europe after the Romans departed in AD 410?", ["The Gepids", "The Jutes", "The Frisians", "The Burgundians"], 1, "Britain was heavily invaded by tribes known as the Jutes, the Angles, and the Saxons.", "The Jutes joined the invasion of early Britain!"],
  [134, "Government & Law", "What is the Commonwealth of Nations?", ["A strictly military alliance between European nations.", "An association of countries supporting democracy and shared development.", "A trade agreement entirely between the UK and the United States.", "A charitable organization dedicated solely to environmental protection."], 1, "The Commonwealth is a voluntary association of independent countries working together towards shared democratic goals.", "A wealth of countries working towards common goals!"],

  // --- EXAM 17 ---
  [135, "Government & Law", "Which of the following is explicitly NOT considered a constitutional institution in the UK?", ["The Parliament", "The Cabinet", "The armed forces", "The local police"], 2, "While the Parliament, Cabinet, and police are core institutions, the armed forces are not classed as a constitutional institution.", "The army defends the nation, but it doesn't govern it!"],
  [136, "History", "During the middle of the 19th century, the catastrophic failure of which crop caused a massive famine in Ireland?", ["The corn crop.", "The potato crop.", "The wheat crop.", "The oat crop."], 1, "The complete failure of the potato crop caused a devastating famine, resulting in millions of deaths and mass emigration.", "The failure of the potato crop caused the famine!"],
  [137, "Government & Law", "What name is given to the group of senior opposition MPs appointed by the leader of the opposition to challenge the government?", ["The Shadow Cabinet", "The Lobbying groups", "The Civil Service", "The Support peers"], 0, "Senior opposition MPs form the 'Shadow Cabinet', whose role is to challenge the government's policies directly.", "The Shadows sit opposite the real Cabinet!"],
  [138, "Government & Law", "What are two core responsibilities of a Member of Parliament (MP)?", ["To protect life and property within their constituency.", "To represent all of their constituents and to actively scrutinise the government.", "To act as politically neutral civil servants for the state.", "To directly appoint new members of the House of Lords."], 1, "MPs are expected to represent everyone in their constituency and to debate and scrutinise government policies.", "MPs must represent the people and scrutinise the laws!"],
  [139, "History", "In 1688, who was formally invited by prominent English Protestants to invade England and take the throne?", ["The Duke of Medina Sidonia", "Emperor Napoleon Bonaparte", "King Philip II of Spain", "William of Orange"], 3, "During the Glorious Revolution of 1688, William of Orange was invited to invade and depose the Catholic King James II.", "The Dutch William of Orange sailed in to take the crown!"],
  [140, "History", "Which king was decisively defeated by William of Orange at the Battle of the Boyne in 1690?", ["King James I", "King James II", "King Richard I", "King Richard II"], 1, "William of Orange defeated the recently deposed King James II at the Battle of the Boyne in Ireland.", "James II lost the battle and his remaining power!"],
  [141, "History", "What sweeping reform did the historic Factories Act of 1847 introduce?", ["It limited the number of hours that absolutely everybody could work to 10 hours per day.", "It significantly increased the number of hours that women and children could work.", "It dramatically increased the number of hours that men could legally work.", "It strictly limited the number of hours that women and children could work to 10 hours per day."], 3, "The Factories Act of 1847 was a landmark reform that limited the working hours of women and children to a maximum of 10 hours per day.", "Women and children were capped at 10 hours a day!"],
  [142, "Government & Law", "What is the official name given to the senior MPs from the main opposition party?", ["The Roundheads", "The Cavaliers", "The Shadow Cabinet", "The Quakers"], 2, "Senior opposition MPs form the Shadow Cabinet to officially put forward alternative policies.", "The Shadow Cabinet challenges the ruling party!"],
  [143, "Government & Law", "In which of the following crucial policy areas does the Scottish Parliament have the power to legislate?", ["National education.", "National immigration.", "National security.", "National defence."], 0, "The Scottish Parliament has devolved powers to legislate on matters such as civil law, health, and education.", "Scotland retains full control over its own schools!"]
];
