/* ==================================================================================
       LIFE IN THE UK: 17 MOCK EXAMS QUESTION BANK (408 Qs)
       Accounts for exactly 17 exams (17 x 24). 
       Includes all visible questions from the 17 PDFs + syllabus completion.
================================================================================== */

const c1 = "Values & Principles";
const c2 = "Geography & Identity";
const c3 = "History";
const c4 = "Modern Society & Culture";
const c5 = "Government & Law";

window.EXAM_QUESTIONS_408 = [
  // --- EXAM 01 ---
  [1, c1, "What are two responsibilities that you will have as a British citizen?", ["Look after area/environment & family", "Stay in UK forever", "Work locally", "None"], 0, "Citizens must look after their family and the local environment.", "Respect & Protect!"],
  [2, c2, "Where is Big Ben located?", ["Buckingham Palace", "Tower of London", "Trafalgar Square", "Houses of Parliament"], 3, "Big Ben is the great bell at the Houses of Parliament.", "Ben is in the House!"],
  [3, c3, "When were men and women given the right to vote at the age of 21?", ["1918", "1903", "1928", "1923"], 2, "In 1928, women were given the right to vote at 21, the same as men.", "28 is great for women's voting fate!"],
  [4, c2, "Where is the UK geographically located?", ["South west of Europe", "North east of Europe", "North west of Europe", "South east of Europe"], 2, "The UK is located in the north west of Europe.", "North West is best!"],
  [5, c5, "How are solicitors' charges usually based?", ["Nature of case", "Time spent on case", "Fixed fee", "Judge's order"], 1, "Solicitors usually charge based on the time they spend.", "Time is money for solicitors!"],
  [6, c5, "Which TWO types of media have to give balanced political coverage by law?", ["Internet & Newspapers", "Newspapers & Radio", "Television & Radio", "Internet & TV"], 2, "TV and Radio must be balanced by law.", "Radio and TV must be equal and free!"],
  [7, c2, "Which territory is a Crown dependency but NOT part of the UK?", ["Northern Ireland", "Wales", "The Channel Islands", "Scotland"], 2, "Channel Islands are Crown dependencies, not part of the UK.", "Channel your dependency!"],
  [8, c3, "What did Sir Frank Whittle invent in the 1930s?", ["Radar", "Hovercraft", "Jet engine", "Ballpoint pen"], 2, "Sir Frank Whittle developed the jet engine.", "Whittle it down to a jet!"],
  [9, c4, "Who wrote 'The Daffodils'?", ["William Blake", "Robert Browning", "Lord Byron", "William Wordsworth"], 3, "Wordsworth wrote The Daffodils.", "Words have worth like Daffodils!"],
  [10, c3, "Who was given the title of Lord Protector?", ["Charles I", "Charles II", "Winston Churchill", "Oliver Cromwell"], 3, "Cromwell was Lord Protector from 1653-1658.", "Cromwell protected the realm!"],
  [11, c4, "What are the 40 days before Easter called?", ["Diwali", "Lent", "Hannukah", "Vaisakhi"], 1, "Lent is the 40 days before Easter.", "Lent is 40 days spent!"],
  [12, c3, "When did the first farmers arrive in Britain?", ["10,000 years ago", "6,000 years ago", "15,000 years ago", "2,000 years ago"], 1, "The first farmers arrived about 6,000 years ago.", "Farming has 6 letters -> 6k years!"],
  [13, c3, "What monument in Wiltshire is a famous prehistoric stone circle?", ["Hadrian's Wall", "Stonehenge", "Skara Brae", "Maiden Castle"], 1, "Stonehenge is the most famous prehistoric monument.", "Stone-henge in Wilts!"],
  [14, c3, "Where is Skara Brae located?", ["Scotland", "Wales", "England", "Northern Ireland"], 0, "Skara Brae is on Orkney, Scotland.", "Skara Brae is a Scottish Brae!"],
  [15, c3, "What metal began to be used in Britain around 4,000 years ago?", ["Iron", "Bronze", "Steel", "Copper"], 1, "The Bronze Age began 4,000 years ago.", "Bronze is 2 metals -> 4k years!"],
  [16, c3, "What was Maiden Castle used for in the Iron Age?", ["Palace", "Hill fort", "Temple", "Port"], 1, "Maiden Castle is an Iron Age hill fort.", "Maiden needs a fort!"],
  [17, c3, "Who led the first unsuccessful Roman invasion in 55 BC?", ["Claudius", "Hadrian", "Julius Caesar", "Constantine"], 2, "Caesar led the first failed expeditions.", "Caesar came first but failed!"],
  [18, c3, "When did Emperor Claudius successfully invade Britain?", ["55 BC", "43 AD", "1066 AD", "1215 AD"], 1, "Claudius invaded in 43 AD.", "C looks like a crescent moon (4-3)."],
  [19, c3, "Who was Queen Boudicca?", ["Roman Queen", "Leader of Iceni tribe", "Norman Queen", "Wife of Alfred"], 1, "Boudicca rebelled against the Romans.", "Iceni no reason to serve Rome!"],
  [20, c3, "How long did the Romans occupy Britain?", ["100 years", "200 years", "400 years", "800 years"], 2, "They remained for 400 years.", "4 centuries of Roman roads!"],
  [21, c3, "Which tribes invaded after the Romans left?", ["Normans", "Angles, Saxons, Jutes", "Celts", "Phoenicians"], 1, "Angles, Saxons, and Jutes invaded.", "ASJ = Anglo-Saxons Joined!"],
  [22, c3, "Where did St Columba establish a monastery?", ["Canterbury", "Iona", "Glastonbury", "Lindisfarne"], 1, "He founded it on Iona.", "Columba to Iona!"],
  [23, c3, "Who converted the Anglo-Saxons to Christianity in 597 AD?", ["St Patrick", "St Augustine", "St Columba", "St Aidan"], 1, "St Augustine became Archbishop of Canterbury.", "Augustine in August!"],
  [24, c3, "Who defeated the Vikings and united England?", ["Harold", "Alfred the Great", "Edward", "Arthur"], 1, "King Alfred the Great defeated the Vikings.", "Alfred cooked a great defense!"],

  // --- EXAM 02 ---
  [25, c5, "What is the Home Secretary responsible for?", ["Health", "Defence", "Education", "Policing"], 3, "The Home Secretary handles crime, policing, and immigration.", "Home is safe with policing!"],
  [26, c2, "St Helena is a British overseas territory and part of the UK.", ["True", "False", "", ""], 1, "False, it is linked to the UK but not part of it.", "St Helena is overseas!"],
  [27, c5, "Several Church of England bishops sit in the House of Lords.", ["True", "False", "", ""], 0, "True, senior bishops sit in the Lords.", "Bishops sit with Lords!"],
  [28, c5, "When walking your dog in public, you must ensure:", ["No playing", "It wears a collar showing owner name/address", "High vis jacket", "No barking"], 1, "Dogs need a collar with name and address.", "Collar up your pup!"],
  [29, c3, "Women over 30 were given the vote due to their effort in which war?", ["WWII", "Crimean War", "WWI", "Civil War"], 2, "WWI efforts helped women over 30 get the vote in 1918.", "WWI won women the vote!"],
  [30, c3, "Which was the last successful foreign invasion of England in 1066?", ["Viking", "Anglo-Saxon", "Roman", "Norman Conquest"], 3, "The Norman Conquest was the last successful invasion.", "Normans knocked last in 1066!"],
  [31, c2, "Where are the Crown Jewels kept?", ["House of Commons", "Tower of London", "Buckingham Palace", "Windsor Castle"], 1, "They are kept at the Tower of London.", "Jewels in the Tower!"],
  [32, c4, "Which sport traces back to 15th century Scotland?", ["Golf", "Tennis", "Football", "Rugby"], 0, "The modern game of golf started in Scotland.", "Golfing in the Highlands!"],
  [33, c3, "Who was the first person in England to print books?", ["Shakespeare", "Barbour", "Chaucer", "William Caxton"], 3, "William Caxton introduced the printing press.", "Caxton printed a ton!"],
  [34, c5, "Which court deals with minor criminal cases in England and Wales?", ["High Court", "Justice of the Peace", "Magistrates' Court", "Crown Court"], 2, "Magistrates' Court handles minor crimes in E&W.", "Magistrates handle the minor stuff!"],
  [35, c3, "What did John Logie Baird develop?", ["Television", "Radar", "PC", "Radio"], 0, "Baird developed television in the 1920s.", "Baird broadcasted the first TV!"],
  [36, c3, "What established the Danelaw?", ["Agreement with Vikings", "Roman law", "Norman rule", "Magna Carta"], 0, "King Alfred made a boundary agreement with the Vikings.", "Danelaw = Danish Law!"],
  [37, c3, "When was the Battle of Hastings?", ["1066", "1215", "1485", "1588"], 0, "The Battle of Hastings was in 1066.", "1066 ultimate stamp!"],
  [38, c3, "Who was killed at the Battle of Hastings?", ["William", "King Harold", "Alfred", "Edward"], 1, "King Harold was killed.", "Harold got an arrow in the eye!"],
  [39, c3, "What tapestry commemorates the Norman Conquest?", ["Rhuddlan", "Bayeux", "Wilton", "Gobelin"], 1, "The Bayeux Tapestry shows 1066 events.", "Bayeux rhymes with Eye!"],
  [40, c3, "Which book was a 1086 survey commissioned by William I?", ["Magna Carta", "Domesday Book", "Canterbury Tales", "Chronicle"], 1, "The Domesday Book surveyed land and property.", "Domesday is Doomsday for tax!"],
  [41, c3, "Which family ruled after the Normans?", ["Plantagenets", "Tudors", "Stuarts", "Windsors"], 0, "The Plantagenets ruled next.", "Plantagenets planted power!"],
  [42, c3, "What document was King John forced to sign in 1215?", ["Bill of Rights", "Magna Carta", "Act of Settlement", "Habeas Corpus"], 1, "The Magna Carta established rule of law.", "Magna Carta on the john!"],
  [43, c3, "Battle in 1415 where Henry V defeated the French?", ["Hastings", "Bannockburn", "Agincourt", "Waterloo"], 2, "The Battle of Agincourt.", "Archers at Agincourt!"],
  [44, c3, "Who fought the Wars of the Roses?", ["Windsor & Tudor", "Lancaster & York", "Stuart & Orange", "Hanover & Bruce"], 1, "House of Lancaster and House of York.", "Lancaster Red, York White!"],
  [45, c3, "Which battle ended the Wars of the Roses?", ["Hastings", "Bannockburn", "Bosworth Field", "Marston Moor"], 2, "Battle of Bosworth Field in 1485.", "Bosworth finished the Roses!"],
  [46, c3, "How many wives did Henry VIII have?", ["Three", "Four", "Six", "Eight"], 2, "He had six wives.", "Divorced, Beheaded, Died... (6)!"],
  [47, c3, "Who was known as 'Bloody Mary'?", ["Elizabeth I", "Mary I", "Mary Queen of Scots", "Queen Anne"], 1, "Mary I persecuted Protestants.", "Bloody Mary I!"],
  [48, c3, "When did the English defeat the Spanish Armada?", ["1215", "1485", "1588", "1605"], 2, "The Armada was defeated in 1588.", "88 looks like sea waves!"],

  // --- EXAM 03 ---
  [49, c1, "Which of the following is a fundamental principle of British life?", ["Communism", "Intolerance", "Individual liberty", "Inequity"], 2, "Individual liberty is a core British value.", "Liberty for all!"],
  [50, c4, "Wales has its own established church.", ["True", "False", "", ""], 1, "False, there is no established church in Wales or NI.", "No church state in Wales!"],
  [51, c4, "What is New Year's Eve called in Scotland?", ["Vaisakhi", "Hannukah", "Diwali", "Hogmanay"], 3, "In Scotland, it is called Hogmanay.", "Hogmanay for the new day!"],
  [52, c3, "Why did Henry VIII establish the Church of England?", ["Protestantism", "Pope refused divorce", "Unite UK", "Rebellion"], 1, "He needed Pope's approval to divorce Catherine of Aragon.", "Henry wanted a divorce!"],
  [53, c3, "What is the long war English kings fought with France in the middle ages?", ["Crimean War", "WWI", "Hundred Years War", "Boer War"], 2, "The Hundred Years War was fought with France.", "100 years of fighting France!"],
  [54, c3, "Why did the British government anger the American colonies?", ["Wanted king", "Tried to tax them", "No jobs", "Religious freedom"], 1, "The British government wanted to tax the colonies.", "No tax without a voice!"],
  [55, c3, "When did the Black Death take place?", ["Golden Age", "Stone Age", "Middle Ages", "Iron Age"], 2, "It arrived in 1348 during the Middle Ages.", "Black Death in the Middle Ages!"],
  [56, c3, "Who was the leader of the suffragettes?", ["Queen Victoria", "Oliver Cromwell", "Florence Nightingale", "Emmeline Pankhurst"], 3, "Emmeline Pankhurst led the suffragettes.", "Pankhurst pushed for the vote!"],
  [57, c2, "Cardiff is the capital city of which country?", ["Scotland", "Northern Ireland", "Ireland", "Wales"], 3, "The capital city of Wales is Cardiff.", "Cardiff for the Welsh!"],
  [58, c3, "During the Great Depression, which industry was badly affected?", ["Housing", "Shipbuilding", "Automobile", "Aviation"], 1, "Heavy industries like shipbuilding were badly affected.", "Ships stopped building in the 30s!"],
  [59, c4, "First man in the world to run 1 mile in under 4 minutes?", ["Chris Hoy", "Roger Bannister", "David Weir", "Mo Farah"], 1, "Sir Roger Bannister ran it in 1954.", "Bannister ran the fastest mile!"],
  [60, c4, "Which festival celebrates the end of Ramadan?", ["Hannukah", "Vaisakhi", "Eid ul Adha", "Eid al-Fitr"], 3, "Eid al-Fitr celebrates the end of Ramadan.", "Fitr finishes the fast!"],
  [61, c3, "Who succeeded Elizabeth I to the English throne?", ["Charles I", "James I", "James II", "William"], 1, "James VI of Scotland became James I.", "Six and One for James!"],
  [62, c3, "What was the Gunpowder Plot of 1605?", ["Assassinate King", "Blow up Parliament", "Irish rebellion", "Cromwell plot"], 1, "A Catholic conspiracy to blow up Parliament.", "Remember the 5th of Nov!"],
  [63, c3, "Who fought in the English Civil War?", ["English vs French", "Royalists vs Parliamentarians", "Saxons vs Vikings", "Tudors vs Stuarts"], 1, "Cavaliers vs Roundheads.", "Fancy Kings vs Round Parliaments!"],
  [64, c3, "What happened to King Charles I in 1649?", ["Fled", "Executed", "Exiled", "Restored"], 1, "He was executed and England became a republic.", "Charles lost his head!"],
  [65, c3, "What was the Restoration of 1660?", ["Bill of Rights", "Monarchy returns", "Union", "Fall of Rome"], 1, "Charles II returned from exile.", "Restored the party King!"],
  [66, c3, "Who was invited to take the throne in 1688?", ["Charles II", "James II", "William of Orange", "George I"], 2, "William of Orange took the throne.", "Orange invasion!"],
  [67, c3, "What did the Bill of Rights 1689 confirm?", ["Magna Carta", "Parliament's rights", "Habeas Corpus", "Settlement"], 1, "It limited monarch power and confirmed Parliament's rights.", "Parliament handed the King a Bill!"],
  [68, c3, "What did the Act of Union 1707 do?", ["United England/Ireland", "United England/Scotland", "England/Wales", "GB/NI"], 1, "United Parliaments of Scotland and England.", "Scotland and England became one!"],
  [69, c3, "Who was the first Prime Minister?", ["Churchill", "Robert Walpole", "Attlee", "Pitt"], 1, "Sir Robert Walpole was the first PM.", "Walpole the first PM!"],
  [70, c3, "Who were the Huguenots?", ["Puritans", "French Protestants", "Fenians", "Quakers"], 1, "French Protestants who fled to England.", "Huge knots of refugees!"],
  [71, c3, "Who defeated Napoleon at Waterloo?", ["Nelson", "Wellington", "Cromwell", "George III"], 1, "Duke of Wellington defeated Napoleon.", "Wellington booted Napoleon!"],
  [72, c3, "What did the Emancipation Act 1833 do?", ["Magna Carta", "Reform", "Abolished slavery", "Welfare"], 2, "It abolished slavery in the British Empire.", "33 freed them!"],

  // --- EXAM 04 ---
  [73, c3, "What was the last battle between Great Britain and France?", ["Trafalgar", "Waterloo", "Hastings", "Agincourt"], 1, "In 1815, Napoleon was defeated at Waterloo.", "Waterloo ended the French wars!"],
  [74, c2, "Which flower is associated with Wales?", ["Daffodil", "Rose", "Shamrock", "Thistle"], 0, "The daffodil represents Wales.", "Daffodils for Wales!"],
  [75, c3, "During Charles II's reign, what caused destruction in London?", ["War", "Flood", "Fire", "Earthquake"], 2, "The Great Fire of 1666.", "Fire in 66!"],
  [76, c5, "How often are general elections held in the UK?", ["Every 3 years", "Every 4 years", "Every 5 years", "Every 10 years"], 2, "They are held at least every five years.", "Vote every 5 years!"],
  [77, c2, "Scotland has its own banknotes, valid everywhere in the UK.", ["True", "False", "", ""], 0, "True, Scottish banknotes are valid across the UK.", "Scottish notes work everywhere!"],
  [78, c5, "What charity preserves buildings, coastline and countryside?", ["Shelter", "Age UK", "Crisis", "The National Trust"], 3, "The National Trust preserves heritage.", "Trust them with the buildings!"],
  [79, c4, "What type of character was played by Charlie Chaplin?", ["Superhero", "Tramp", "Genius", "Bandit"], 1, "He became famous for his tramp character.", "Chaplin was the Tramp!"],
  [80, c5, "You have to be at least 21 years old to stand as MP.", ["True", "False", "", ""], 1, "False, you only need to be 18.", "18 to stand for MP!"],
  [81, c3, "Who developed the radar?", ["John Logie Baird", "Frank Whittle", "Christopher Cockrell", "Robert Watson-Watt"], 3, "Sir Robert Watson-Watt developed radar.", "Watson-Watt watched the radar!"],
  [82, c5, "Where is the official home of the Prime Minister?", ["18 Oxford Street", "Buckingham Palace", "Windsor Castle", "10 Downing Street"], 3, "The official home is 10 Downing Street.", "Number 10 for the PM!"],
  [83, c5, "Which TWO media have to give balanced political coverage?", ["TV & Internet", "Internet & Newspapers", "Newspapers & Radio", "Television & Radio"], 3, "TV and Radio must be balanced by law.", "Broadcasts must be balanced!"],
  [84, c3, "Who split the atom in 1932?", ["Tim Berners-Lee", "Frank Whittle", "Ernest Rutherford", "Peter Mansfield"], 2, "Ernest Rutherford led the team.", "Rutherford split the nut/atom!"],
  [85, c3, "What does the 'Dunkirk spirit' refer to?", ["High morale", "Civilian boat rescue", "London Blitz", "RAF victory"], 1, "Rescue of Allied soldiers by small boats.", "Civilian boat rescue!"],
  [86, c3, "What was the aerial battle over Britain in 1940?", ["Jutland", "Battle of Britain", "Somme", "Blitz"], 1, "The Battle of Britain.", "RAF skies defense!"],
  [87, c3, "What was 'The Blitz'?", ["Invasion of Poland", "Nighttime bombing of cities", "Naval blockade", "Normandy"], 1, "The nighttime bombing of British cities.", "Sudden bombing campaign!"],
  [88, c3, "When did the UK join the EEC?", ["1957", "1973", "1992", "2016"], 1, "The UK joined in 1973.", "Joined in 73!"],
  [89, c3, "When was the Falklands War?", ["1979", "1982", "1991", "2003"], 1, "It was fought in 1982.", "Falklands in 82!"],
  [90, c3, "Who introduced free secondary education in 1944?", ["Churchill", "Attlee", "R.A. Butler", "Macmillan"], 2, "R.A. Butler introduced the 1944 Education Act.", "Butler served up free schools!"],
  [91, c3, "When did WWI end?", ["11 Nov 1914", "11 Nov 1918", "8 May 1945", "11 Nov 1945"], 1, "WWI ended on 11 Nov 1918.", "11th hour, 11th day, 1918!"],
  [92, c3, "Who led the Highland Clearances?", ["Clans", "Landlords evicting crofters", "Protestants", "Canal builders"], 1, "Crofters were evicted for sheep farming.", "Cleared for sheep!"],
  [93, c3, "Who campaigned to improve child working conditions?", ["Shaftesbury", "Wilberforce", "Owen", "Attlee"], 0, "Lord Shaftesbury championed factory acts.", "Shaftesbury shut the mine shafts!"],
  [94, c3, "What did Elizabeth Fry reform?", ["Hospitals", "Prisons", "Child labor", "Schools"], 1, "She reformed prison conditions.", "Fry set prisoners free!"],
  [95, c3, "Which airliner was developed by Britain and France?", ["Concorde", "Spitfire", "Comet", "Hurricane"], 0, "Concorde was the supersonic airliner.", "Concorde for French-UK flight!"],
  [96, c3, "Who was murdered in Canterbury Cathedral in 1170?", ["French general", "Thomas Becket", "Peasant", "Printer"], 1, "Thomas Becket was murdered by knights.", "Becket at the altar!"],

  // --- EXAM 05 ---
  [97, c4, "When does Easter take place?", ["Nov/Dec", "Jan/Feb", "March or April", "May/Jun"], 2, "Easter takes place in March or April.", "Easter in the Spring!"],
  [98, c2, "Which of the following is not a valid UK coin?", ["1p", "5p", "25p", "£1"], 2, "There are no 25p coins in the UK.", "No quarter coins in UK!"],
  [99, c2, "Where is the Eden Project located?", ["Dorset", "Cornwall", "Devon", "Somerset"], 1, "It is located in Cornwall.", "Eden is in Cornwall!"],
  [100, c2, "St Helena and Falkland Islands are part of Great Britain.", ["True", "False", "", ""], 1, "False, they are overseas territories.", "Overseas, not GB!"],
  [101, c1, "Which two are fundamental principles of British life?", ["Monarchy", "The rule of law & Democracy", "Join a party", "Isolationism"], 1, "The rule of law and democracy.", "Law and Democracy rule!"],
  [102, c5, "What kind of charity is 'Friends of the Earth'?", ["Environmental", "Medical", "Pets", "Older people"], 0, "Friends of the Earth is an environmental charity.", "Friends of Earth protect nature!"],
  [103, c5, "If a husband forces his wife to have sex he can be charged with rape.", ["True", "False", "", ""], 0, "True, rape within marriage is a crime.", "Consent is always required!"],
  [104, c3, "Where did the Boer War take place?", ["Netherlands", "Falklands", "Gibraltar", "South Africa"], 3, "It took place in South Africa.", "Boers fought in South Africa!"],
  [105, c5, "Which action is known as 'canvassing'?", ["Donating blood", "Volunteering", "Caring for animals", "Persuading people to vote"], 3, "Canvassing is persuading people to vote for a party.", "Canvassing is campaigning!"],
  [106, c4, "Best-loved novel in 2003 poll?", ["Oliver Twist", "James Bond", "Pride and Prejudice", "The Lord of the Rings"], 3, "Lord of the Rings was voted best-loved.", "Tolkien's ring is best loved!"],
  [107, c3, "When did Germany invade Poland?", ["1942", "1941", "1940", "1939"], 3, "Hitler invaded Poland in 1939.", "39 started the line!"],
  [108, c3, "What did Simon de Montfort's Parliament introduce?", ["Monarchy", "Elected representatives", "House of Lords", "Prime Minister"], 1, "It introduced elected representatives in 1265.", "De Montfort invited commoners!"],
  [109, c3, "What did the Second Reform Act 1867 do?", ["Abolish monarchy", "Vote to urban working men", "Women franchise", "Age 18 vote"], 1, "It extended the vote to urban working-class men.", "Urban workers gained power!"],
  [110, c3, "Which treaty brought peace to Northern Ireland in 1998?", ["Utrecht", "Good Friday Agreement", "Versailles", "Anglo-Irish"], 1, "The Good Friday Agreement.", "Good Friday brought peace!"],
  [111, c3, "Who opened the first curry house in Britain?", ["Sake Dean Mahomet", "Queen Victoria", "Churchill", "Nelson"], 0, "Sake Dean Mahomet in 1810.", "Mahomet brought the spice!"],
  [112, c3, "Which statute annexed Wales to England?", ["Magna Carta", "Statute of Rhuddlan", "Act of Union", "Bill of Rights"], 1, "The Statute of Rhuddlan in 1284.", "Rhuddlan rules Wales!"],
  [113, c3, "Who were the Boers?", ["Vikings", "Dutch settlers in South Africa", "French Protestants", "Soldiers"], 1, "Settlers of Dutch descent in South Africa.", "Boers were Dutch farmers!"],
  [114, c3, "Where was the Great Exhibition of 1851 held?", ["Dome", "Crystal Palace", "St Paul's", "Royal Crescent"], 1, "Inside the Crystal Palace.", "Glass Palace for 1851!"],
  [115, c3, "When did Oliver Cromwell rule?", ["1610s", "1650s", "1680s", "1710s"], 1, "He ruled in the 1650s as Lord Protector.", "Cromwell in the 50s!"],
  [116, c3, "The Act of Union 1707 established which parliament?", ["Great Britain", "UK", "English", "Commonwealth"], 0, "The Parliament of Great Britain.", "1707 made Great Britain!"],
  [117, c3, "What did the Emancipation Act 1833 abolish?", ["Magna Carta", "Reform", "Slavery", "Bill of Rights"], 2, "It abolished slavery throughout the empire.", "33 freed slaves!"],
  [118, c3, "Which era is associated with rapid industrialization?", ["Victorian Era", "Tudor Period", "Middle Ages", "Restoration"], 0, "The Victorian Era.", "Victoria's industrial age!"],
  [119, c3, "Main purpose of Magna Carta?", ["Limit King's power", "Taxation", "Parliament", "Independence"], 0, "To limit the King's power and establish rule of law.", "Limited the absolute King!"],
  [120, c3, "Which document established constitutional monarchy in 1689?", ["Bill of Rights", "Magna Carta", "Habeas Corpus", "Settlement"], 0, "The Bill of Rights.", "Bill of Rights for Parliament!"],

  // --- EXAM 06 ---
  [121, c1, "As a British citizen what are two responsibilities?", ["Respect/obey law & Look after family", "Walk dog", "Go to church", "None"], 0, "Respecting the law and looking after family are key.", "Respect and protect family!"],
  [122, c3, "Who made the first coins to be minted in Britain?", ["Stone Age", "Anglo-Saxons", "Iron Age", "Romans"], 2, "The people of the Iron Age made the first coins.", "Iron coins first!"],
  [123, c2, "Who built the Tower of London?", ["William the Conqueror", "Queen Victoria", "Queen Elizabeth I", "Oliver Cromwell"], 0, "William the Conqueror built it.", "Conqueror built the Tower!"],
  [124, c2, "What are national parks?", ["Greenhouses", "Volcanic lava", "Protected countryside", "Medieval buildings"], 2, "National Parks are areas of protected countryside.", "Parks protect the country!"],
  [125, c3, "What was a survey commissioned by William I?", ["Magna Carta", "Domesday Book", "Bayeux Tapestry", "Canterbury Tales"], 1, "The Domesday Book surveyed land and property.", "Domesday counted everything!"],
  [126, c3, "Why was 'Home Rule' for Ireland delayed in 1914?", ["WWI outbreak", "WWII outbreak", "No king", "Black Death"], 0, "The outbreak of WWI delayed it.", "WWI delayed Home Rule!"],
  [127, c3, "Which is true about Elizabeth I?", ["Protestant finding balance", "Catholic finding balance", "Muslim", "Atheist"], 0, "She was Protestant and succeeded in finding a balance.", "Elizabeth balanced religion!"],
  [128, c5, "Which two documents for a National Insurance number?", ["Identity & Permission to work", "Tenancy", "Contract", "Identity"], 0, "Documents proving identity and permission to work.", "Prove identity and work right!"],
  [129, c3, "When was the Statute of Rhuddlan enacted?", ["1066", "1215", "1284", "1314"], 2, "Enacted in 1284, annexing Wales.", "1284 rules Wales!"],
  [130, c3, "Which King was killed at Bosworth Field in 1485?", ["Henry VII", "Richard III", "Edward IV", "Charles I"], 1, "Richard III was killed.", "Richard fell at Bosworth!"],
  [131, c3, "What was the Habeas Corpus Act of 1679?", ["Abolish slavery", "Prevent unlawful imprisonment", "Window tax", "Vote"], 1, "Guarantees you cannot be held unlawfully.", "Have the body in court!"],
  [132, c3, "What did the Repeal of the Corn Laws in 1846 achieve?", ["Banned corn", "Allowed cheap raw materials import", "Abolished monarchy", "Moved farmers"], 1, "Lowered food prices by allowing imports.", "Repealed tariffs!"],
  [133, c3, "What was the population of the UK in 1801?", ["2 million", "8 million", "40 million", "60 million"], 1, "It was around 8 million in 1801.", "8 million in 1801!"],
  [134, c3, "What was promised to Ireland in 1913?", ["Independence", "Home Rule", "Representation", "Aid"], 1, "Home Rule was promised but delayed.", "Home Rule promised!"],
  [135, c3, "Main cause of English Civil War?", ["Trade dispute", "King tried to rule without Parliament", "Armada", "Succession"], 1, "Charles I tried to rule without Parliament.", "King ignored Parliament!"],
  [136, c3, "Which acts joined England and Wales?", ["Union 1707", "Laws in Wales Acts", "Rhuddlan", "Magna Carta"], 1, "Laws in Wales Acts 1536-1542.", "Henry VIII united Wales!"],
  [137, c3, "Result of Battle of Agincourt in 1415?", ["French won", "English defeated French", "Armada destroyed", "Romans left"], 1, "English won despite being outnumbered.", "Archers won Agincourt!"],
  [138, c3, "Population of UK in 1901?", ["10 million", "20 million", "40 million", "60 million"], 2, "It was around 40 million.", "40 million in 1901!"],
  [139, c3, "Which King killed at Hastings?", ["Edward", "Harold", "William", "Richard"], 1, "King Harold was killed.", "Harold's eye!"],
  [140, c3, "During which war did Agincourt take place?", ["Crimean", "Hundred Years War", "Roses", "Civil War"], 1, "The Hundred Years War.", "100 years of fighting!"],
  [141, c3, "Colonies declaring independence in 1776?", ["North African", "Asian", "North American", "South African"], 2, "13 North American colonies.", "America 1776!"],
  [142, c3, "Who fought the English Civil War?", ["York/Lancaster", "Saxons/Vikings", "Cavaliers and Roundheads", "Fraser/Stuart"], 2, "Cavaliers vs Roundheads.", "Cavaliers vs Roundheads!"],
  [143, c3, "Huguenots came from where?", ["Pakistan", "Germany", "India", "France"], 3, "They were French Protestants.", "French refugees!"],
  [144, c3, "Who defeated English at Bannockburn?", ["Charles I", "James I", "Nelson", "Robert the Bruce"], 3, "Robert the Bruce kept Scotland free.", "Bruce bruised the English!"],

  // --- EXAM 07 ---
  [145, c1, "As a British citizen, you should:", ["Respect law & Look after area", "Vote all", "Religious activities", "None"], 0, "Respecting the law and environment are responsibilities.", "Respect your area!"],
  [146, c4, "When is Halloween celebrated?", ["5 Nov", "11 Nov", "31 Oct", "1 Apr"], 2, "Halloween is October 31st.", "Spooky 31st!"],
  [147, c3, "The Bill of Rights 1689 gave women the right to vote.", ["True", "False", "", ""], 1, "False, it limited the king's power.", "Bill limited the King!"],
  [148, c4, "Most famous cricket competition between England and Australia?", ["The Ashes", "Six Nations", "Grand National", "Australian Open"], 0, "The Ashes is the famous test series.", "Burn stumps to Ashes!"],
  [149, c3, "Biggest source of employment in the 18th century?", ["Fishing", "Teaching", "Aircraft", "Manufacturing"], 3, "Manufacturing and agriculture.", "Making things in 18th C!"],
  [150, c3, "Movement against Pope during Henry VIII's reign?", ["Inquisition", "Holy Wars", "The Reformation", "Enlightenment"], 2, "It was the Reformation.", "Reforming the church!"],
  [151, c5, "How to apply for National Insurance Number?", ["NHS", "Contact DWP", "MP", "Employer"], 1, "Contact the Department for Work and Pensions.", "DWP for NI!"],
  [152, c4, "Which is a major horse-racing event in England?", ["Wimbledon", "Royal Ascot", "Open Championship", "Six Nations"], 1, "Royal Ascot is a major 5-day event.", "Ascot for horses!"],
  [153, c5, "How many members form a jury in Scotland?", ["12", "14", "15", "20"], 2, "Scotland has 15 jury members.", "15 kilts on a jury!"],
  [154, c4, "What is known as Lent?", ["40 days before Christmas", "40 days after Easter", "40 days before Easter", "40 days after Christmas"], 2, "Lent is 40 days before Easter.", "Lent prepares for Easter!"],
  [155, c3, "When was the last successful foreign invasion of England?", ["1415", "1314", "1066", "1200"], 2, "1066 was the Norman Conquest.", "1066 Norman invasion!"],
  [156, c3, "What is the 'Dunkirk spirit'?", ["Bombing of London", "Civilian boat rescue", "Social classes", "Refugees"], 1, "Civilian volunteers rescued soldiers.", "Civilian boat rescue!"],
  [157, c3, "Charles I believed in 'Divine Right' so he tried:", ["To rule without Parliament", "To rule with approval", "To raise money", "To restore Catholicism"], 0, "He tried to rule without Parliament.", "Charles ignored Parliament!"],
  [158, c3, "What caused the famine in Ireland?", ["Corn", "Potato", "Wheat", "Oats"], 1, "The potato crop failed.", "Potato famine!"],
  [159, c3, "What happened to Charles I after prison?", ["Spain", "Priest", "France", "Executed"], 3, "He was executed in 1649.", "Charles lost his head!"],
  [160, c3, "What kind of disaster was the Black Death?", ["Plague", "Earthquake", "Famine", "Civil war"], 0, "It was a bubonic plague.", "Black Death was a plague!"],
  [161, c3, "Country in conflict with UK over trade in 18th century?", ["Andorra", "Germany", "France", "Luxembourg"], 2, "Britain clashed with France over trade.", "French trade rivalry!"],
  [162, c5, "Does the UK have a single, written constitution?", ["Yes", "No", "", ""], 1, "The UK has an unwritten constitution.", "Unwritten rules!"],
  [163, c5, "What is the Monarch's role?", ["Pass laws", "Neutral Head of State", "Lead party", "Head of Judiciary"], 1, "The King is politically neutral.", "Monarch must be neutral!"],
  [164, c5, "How many MPs in the House of Commons?", ["500", "600", "650", "700"], 2, "There are 650 MPs.", "Six-Fifty seats!"],
  [165, c5, "Who is the 'Speaker'?", ["Leader of Opposition", "Neutral MP keeping order", "PM's deputy", "Civil servant"], 1, "The Speaker chairs debates neutrally.", "Speaker keeps order!"],
  [166, c5, "Role of a Parliamentary 'Whip'?", ["Punish MPs", "Ensure party voting discipline", "Assist Speaker", "Draft bills"], 1, "Whips maintain party discipline.", "Whip them into line!"],
  [167, c5, "Who are 'peers'?", ["Elected councils", "Appointed members of Lords", "Royal family", "Judges"], 1, "Appointed members of the House of Lords.", "Peers are appointed!"],
  [168, c5, "Age to run as an MP?", ["18", "21", "25", "30"], 0, "You can run for office at 18.", "18 to be an MP!"],

  // --- EXAM 08 ---
  [169, c3, "World War II started as a result of Germany invading which country?", ["France", "Russia", "Poland", "Austria"], 2, "Hitler invaded Poland in 1939.", "Poland started WWII!"],
  [170, c2, "Which flower is associated with Scotland?", ["Shamrock", "Rose", "Daffodil", "Thistle"], 3, "The thistle represents Scotland.", "Thistles in the Highlands!"],
  [171, c5, "Police complaints can only be made to the Chief Constable.", ["True", "False", "", ""], 1, "False, you can also complain to the IOPC.", "Independent bodies exist!"],
  [172, c5, "Which is a responsibility of the Home Secretary?", ["Economy", "Crime", "Education", "Defence"], 1, "The Home Secretary handles crime, policing, and immigration.", "Home Sec stops crime!"],
  [173, c4, "When is St David's day celebrated?", ["1 Mar", "17 Mar", "23 Apr", "30 Nov"], 0, "St David's day is 1st March.", "David marches first!"],
  [174, c5, "Which system elects MPs to the Commons?", ["Proportional Representation", "First-Past-the-Post", "Single Transferable Vote", "Alternative Vote"], 1, "First-Past-the-Post is used for General Elections.", "First past the post wins!"],
  [175, c5, "What are Crown Dependencies?", ["Gibraltar", "Self-governing islands (Isle of Man/Channel Islands)", "Counties", "Independent nations"], 1, "Isle of Man and Channel Islands.", "Dependencies have crowns!"],
  [176, c5, "Are British Overseas Territories part of the UK?", ["Yes, full rep", "No, linked but self-governing", "Yes, ruled by Monarch", "No, completely independent"], 1, "They are self-governing but linked.", "Linked but self-governing!"],
  [177, c5, "Which devolved administration sits in Holyrood?", ["Welsh Govt", "Scottish Parliament", "NI Assembly", "London Auth"], 1, "The Scottish Parliament meets at Holyrood.", "Holyrood in Scotland!"],
  [178, c5, "Voting system for Northern Ireland Assembly?", ["First-Past-the-Post", "Single Transferable Vote", "Alternative Vote", "Closed List"], 1, "STV is used for fair representation.", "STV for NI!"],
  [179, c5, "Who is responsible for civil service appointments?", ["Ruling party", "Independent commissions on merit", "Monarch", "Lords"], 1, "Appointed neutrally based on merit.", "Merit, not politics!"],
  [180, c5, "Age of criminal responsibility in Scotland?", ["10", "12", "14", "16"], 1, "It is 12 in Scotland.", "12 in Scotland!"],
  [181, c5, "Who typically hears cases in a Magistrates' Court?", ["High Court Judge", "Unpaid volunteers (Magistrates)", "Sheriff", "MPs"], 1, "Unpaid volunteer lay magistrates hear cases.", "Volunteers judge minor stuff!"],
  [182, c5, "Limit for small claims in Scotland?", ["£3k", "£5k", "£10k", "£15k"], 1, "The limit is £5,000 in Scotland.", "£5k for Scottish claims!"],
  [183, c5, "How are judges appointed?", ["By PM", "Independent commission on merit", "Election", "By Speaker"], 1, "Appointed by an independent commission.", "Independent judges!"],
  [184, c5, "Minor criminal cases in Scotland?", ["Crown Court", "Justice of the Peace", "Magistrates", "Youth Court"], 1, "Justice of the Peace Court handles them.", "Peace for minor crimes!"],
  [185, c5, "Which is NOT devolved to NI Assembly?", ["Education", "Health", "Defence", "Agriculture"], 2, "Defence is handled centrally.", "Defence is central!"],
  [186, c5, "Head of UK Judiciary in E&W?", ["PM", "Lord Chief Justice", "Lord Chancellor", "Monarch"], 1, "The Lord Chief Justice.", "Chief Justice heads it!"],
  [187, c5, "Court handling minor civil disputes E&W?", ["Crown", "Magistrates", "County Court", "High Court"], 2, "County Court handles civil disputes.", "County handles civil!"],
  [188, c5, "Main opposition in House of Commons?", ["Lords", "Second-largest party", "Civil Service", "Judiciary"], 1, "The second-largest party is the Opposition.", "Second place is Opposition!"],
  [189, c5, "Who presides over Commons?", ["PM", "Speaker", "Monarch", "Archbishop"], 1, "The Speaker presides.", "Speaker keeps order!"],
  [190, c5, "Function of a jury?", ["Sentence", "Decide guilty/not guilty", "Arrest", "Constitutional checks"], 1, "Jury decides the verdict.", "Jury decides guilt!"],
  [191, c5, "Age of criminal responsibility in E/W/NI?", ["10", "12", "14", "16"], 0, "It is 10 in England, Wales, and NI.", "10 is the age!"],
  [192, c5, "MP stands for?", ["Member of Parliament", "Minister", "Master", "Mayor"], 0, "Member of Parliament.", "MP = Member of Parliament!"],

  // --- EXAM 09 ---
  [193, c2, "Which flower is associated with Northern Ireland?", ["Daffodil", "Thistle", "Shamrock", "Rose"], 2, "The shamrock represents Northern Ireland.", "Shamrock for NI!"],
  [194, c3, "The last battle between Britain and France was Waterloo.", ["True", "False", "", ""], 0, "True, Waterloo in 1815 was the last battle.", "Waterloo ended it!"],
  [195, c4, "£100 is the highest value note in circulation.", ["True", "False", "", ""], 1, "False, the £50 note is the highest.", "Fifty is top note!"],
  [196, c2, "Where is the Lake District National Park located?", ["Scotland", "Wales", "England", "Northern Ireland"], 2, "It is in England.", "Lakes in England!"],
  [197, c1, "Two responsibilities you will have?", ["Buy local", "Volunteer", "Look after family & Respect rights", "None"], 2, "Respecting others' rights and looking after family.", "Respect and protect!"],
  [198, c4, "Who was born in Stratford-upon-Avon?", ["Jane Austen", "Charles Dickens", "William Shakespeare", "Thomas Hardy"], 2, "William Shakespeare was born there.", "Shakespeare's Stratford!"],
  [199, c3, "What did the Education Act 1944 (Butler Act) introduce?", ["Free uni", "Free primary", "Free secondary in E&W", "Paid schooling"], 2, "It introduced free secondary education.", "Butler served free secondary!"],
  [200, c5, "What is the small claims procedure?", ["Informal minor disputes", "Home insurance", "Serious fraud", "Divorces"], 0, "An informal way to settle minor disputes.", "Small claims, minor disputes!"],
  [201, c3, "Building constructed for Great Exhibition 1851?", ["Crystal Palace", "Buckingham", "Kensington", "Apsley"], 0, "The Crystal Palace.", "Glass Palace for exhibition!"],
  [202, c3, "Who was Florence Nightingale?", ["Economist", "Painter", "Nurse", "Poet"], 2, "She is the founder of modern nursing.", "Nightingale the nurse!"],
  [203, c5, "What does a select committee do?", ["Make laws", "Scrutinise specific govt departments", "Appoint peers", "Choose judges"], 1, "They inspect government department work.", "Select committees inspect!"],
  [204, c5, "Which act prohibits discrimination?", ["Trade Union", "Equality Act 2010", "Wealth", "Education"], 1, "The Equality Act 2010 protects 9 characteristics.", "Equality for all!"],
  [205, c5, "When did same-sex marriage become law (E/W/S)?", ["2005", "2010", "2014", "2020"], 2, "It came into force in 2014.", "2014 marriage equality!"],
  [206, c5, "Main role of civil service?", ["Pass statutes", "Carry out policies neutrally", "Represent UN", "Arrest citizens"], 1, "They neutrally serve the elected government.", "Neutral civil servants!"],
  [207, c5, "Which devolved parliament meets in Cardiff?", ["Senedd", "Stormont", "Welsh Council", "Monmouth"], 0, "The Senedd (Welsh Parliament).", "Senedd is Welsh!"],
  [208, c5, "Which court hears serious civil disputes in London?", ["Magistrates", "High Court", "County", "Crown"], 1, "The High Court handles serious civil claims.", "High Court for big civil!"],
  [209, c5, "Cabinet post responsible for economy/budget?", ["Home Sec", "Foreign Sec", "Chancellor of the Exchequer", "Speaker"], 2, "The Chancellor manages the economy.", "Chancellor writes cheques!"],
  [210, c5, "What is Civil Law mostly concerned with?", ["Crimes", "Disputes between individuals/orgs", "Police", "Treaties"], 1, "It settles private disputes.", "Civil is for citizens!"],
  [211, c5, "Publication listing everything said in Parliament?", ["Times", "Hansard", "Telegraph", "Gazette"], 1, "Hansard is the official report.", "Hansard hears all!"],
  [212, c5, "Spiritual leader of Church of England?", ["Monarch", "Archbishop of Canterbury", "PM", "Pope"], 1, "The Archbishop is the spiritual leader.", "Archbishop leads spiritually!"],
  [213, c5, "Court orders to protect against forced marriage?", ["Yes", "No", "", ""], 0, "Yes, Forced Marriage Protection Orders exist.", "Protection from forced marriage!"],
  [214, c5, "Youth Court cases heard by (E/W/NI)?", ["Specially trained magistrates", "Jury", "Public", "High Judges"], 0, "By up to 3 specially trained magistrates.", "Trained magistrates for youth!"],
  [215, c5, "UK government has never suspended NI Assembly.", ["True", "False", "", ""], 1, "False, it has been suspended previously.", "It has been suspended!"],
  [216, c5, "How to complain about police?", ["Police station & Chief Constable", "Commons", "Army", ""], 0, "Go to station or write to Chief Constable.", "Complain to Chief Constable!"],

  // --- EXAM 10 ---
  [217, c4, "Who is the patron Saint of England?", ["St George", "St Patrick", "St David", "St Andrew"], 0, "St George is the patron saint.", "George slays the dragon!"],
  [218, c2, "Where is Loch Lomond located?", ["England", "Wales", "Scotland", "Northern Ireland"], 2, "It is in western Scotland.", "Loch Lomond in Scotland!"],
  [219, c4, "Wales has its own established church.", ["True", "False", "", ""], 1, "False, there is no established church.", "No state church in Wales!"],
  [220, c4, "Stories associated with Geoffrey Chaucer?", ["Cambridge", "Eastbourne", "Canterbury Tales", "London"], 2, "He wrote the Canterbury Tales.", "Chaucer's Canterbury!"],
  [221, c4, "When is Boxing Day?", ["31 Oct", "26 Dec", "24 Dec", "1 Jan"], 1, "Boxing Day is 26th December.", "Box up on the 26th!"],
  [222, c4, "Holiday when banks and businesses close?", ["Credit", "Branch", "Bank Holidays", "Business"], 2, "They are called Bank Holidays.", "Banks close on Bank Holidays!"],
  [223, c4, "What was Isaac Newton known for?", ["Insulin", "Gravity", "Penicillin", "Steam"], 1, "He discovered gravity.", "Newton's falling apple!"],
  [224, c3, "When did WWI come to an end?", ["1922", "1918", "1945", "1943"], 1, "It ended in 1918.", "1918 WWI end!"],
  [225, c3, "Who built a wall to keep out the Picts?", ["Boudicca", "Hadrian", "Claudius", "Caesar"], 1, "Emperor Hadrian built the wall.", "Hadrian's Wall!"],
  [226, c4, "Universities in Thames rowing race?", ["Oxford & Cambridge", "Manchester & Warwick", "", ""], 0, "Oxford and Cambridge race annually.", "Oxford vs Cambridge row!"],
  [227, c5, "Does Britain have a written constitution?", ["Yes", "No", "", ""], 1, "No, it is an unwritten constitution.", "Unwritten rules!"],
  [228, c4, "National anthem of the UK?", ["Rule, Britannia!", "God Save the King", "Land of Hope", "Jerusalem"], 1, "God Save the King.", "God Save the King!"],
  [229, c4, "When is St Andrew's Day (Scotland)?", ["17 Apr", "31 Dec", "1 Mar", "30 Nov"], 3, "St Andrew's Day is 30th November.", "Andrew in November!"],
  [230, c4, "Flag combining crosses of George, Andrew, Patrick?", ["Welsh Flag", "Royal Standard", "Union Jack", "Commonwealth"], 2, "The Union Jack.", "Union Jack combines them!"],
  [231, c4, "Primary significance of Diwali?", ["Harvest", "Festival of lights", "New Year", "End of fast"], 1, "It is the Festival of Lights.", "Diwali delights with lights!"],
  [232, c4, "Eight-day Jewish festival of lights?", ["Hanukkah", "Passover", "Yom Kippur", "Rosh Hashanah"], 0, "Hanukkah is the Jewish festival of lights.", "Hanukkah lights!"],
  [233, c4, "Victorian novelist wrote 'Oliver Twist'?", ["Austen", "Hardy", "Charles Dickens", "Eliot"], 2, "Charles Dickens.", "Dickens wrote Oliver Twist!"],
  [234, c4, "1981 sports drama film won four Oscars?", ["Third Man", "Chariots of Fire", "Lawrence of Arabia", "Brief Encounter"], 1, "Chariots of Fire.", "Chariots of running Fire!"],
  [235, c4, "What is a 'pantomime'?", ["Silent", "Comedic musical theatre at Christmas", "Parade", "Opera"], 1, "A Christmas comedic play.", "Panto at Christmas!"],
  [236, c4, "Classical music festival over summer?", ["The Proms", "Glastonbury", "Glyndebourne", "Womad"], 0, "The Proms.", "BBC sponsors the Proms!"],
  [237, c4, "Traditional food native to Wales?", ["Haggis", "Welsh cakes", "Ulster Fry", "Yorkshire Pudding"], 1, "Welsh cakes.", "Welsh cakes for Wales!"],
  [238, c4, "Traditional Sunday meal?", ["Fish & Chips", "Curry", "Roast dinner", "Pie"], 2, "A traditional roast dinner.", "Sunday Roast!"],
  [239, c4, "National flower of England?", ["Tudor Rose", "Thistle", "Shamrock", "Daffodil"], 0, "The Tudor Rose.", "Tudor Rose for England!"],
  [240, c4, "Day jokes are published?", ["April Fool's", "Boxing", "Halloween", "Valentine's"], 0, "1st April is April Fool's Day.", "April Fools!"],

  // --- EXAM 11 ---
  [241, c2, "Is St Helena part of the UK?", ["Yes", "No", "", ""], 1, "No, it is a British overseas territory.", "St Helena is overseas!"],
  [242, c2, "Where is Theatreland?", ["Docklands", "East End", "West End", "South End"], 2, "London's West End is Theatreland.", "West End shows!"],
  [243, c2, "What is the name of the UK currency?", ["Euro", "Pound Sterling", "Peso", "Dollar"], 1, "The currency is the Pound Sterling.", "Pound Sterling!"],
  [244, c4, "What other name is given to Diwali?", ["Festival of Lights", "Ash Wednesday", "Good Friday", "Easter Monday"], 0, "It is often called the Festival of Lights.", "Diwali delights with lights!"],
  [245, c3, "What is the Enlightenment?", ["Total peace", "New ideas about politics/science", "Largest empire", "Recovery"], 1, "18th century period of new ideas.", "Enlightened with new ideas!"],
  [246, c5, "Which charity helps the environment?", ["NSPCC", "Shelter", "Friends of the Earth", "Age UK"], 2, "Friends of the Earth (and National Trust).", "Friends of the Earth!"],
  [247, c3, "Who designed St Paul's Cathedral after 1666?", ["Adam", "Christopher Wren", "Foster", "Hadid"], 1, "Sir Christopher Wren designed it.", "Wren rebuilt the cathedral!"],
  [248, c3, "When were the first coins in Britain made?", ["Stone Age", "Bronze Age", "Iron Age", "Middle Ages"], 2, "Iron Age people made the first coins.", "Iron coins first!"],
  [249, c3, "Who was Emmeline Pankhurst?", ["Suffragette", "Nurse", "Doctor", "Scientist"], 0, "She was a leading suffragette.", "Pankhurst pushed for votes!"],
  [250, c3, "Who did Britain fight in the Crimean War?", ["Turkey", "Russia", "France", "Germany"], 1, "Britain fought Russia.", "Crimean War vs Russia!"],
  [251, c5, "How old to buy alcohol in UK?", ["17", "18", "19", "20"], 1, "You must be 18.", "18 for a pint!"],
  [252, c2, "Approx population of the UK?", ["45m", "55m", "67m", "80m"], 2, "It is approximately 67 million.", "67 million people!"],
  [253, c2, "Proportion of UK population in England?", ["50%", "65%", "84%", "95%"], 2, "England holds about 84%.", "England is 84%!"],
  [254, c2, "Highest mountain in Scotland and UK?", ["Snowdon", "Scafell", "Ben Nevis", "Slieve"], 2, "Ben Nevis.", "Ben Nevis is the tallest!"],
  [255, c2, "Highest mountain in Wales?", ["Ben Nevis", "Snowdon", "Scafell", "Slieve"], 1, "Snowdon.", "Snowdon for Wales!"],
  [256, c2, "Highest mountain in England?", ["Ben Nevis", "Snowdon", "Scafell Pike", "Slieve"], 2, "Scafell Pike.", "Scafell in England!"],
  [257, c2, "Highest mountain in Northern Ireland?", ["Ben", "Snowdon", "Scafell", "Slieve Donard"], 3, "Slieve Donard.", "Slieve in NI!"],
  [258, c2, "Body of water separating GB from Ireland?", ["North Sea", "Channel", "Irish Sea", "Celtic Sea"], 2, "The Irish Sea.", "Irish Sea separates them!"],
  [259, c2, "How many National Parks in GB?", ["5", "10", "15", "20"], 2, "There are 15 in total.", "15 National Parks!"],
  [260, c2, "Capital city of Scotland?", ["Glasgow", "Aberdeen", "Dundee", "Edinburgh"], 3, "Edinburgh is the capital.", "Edinburgh capital!"],
  [261, c2, "Capital city of Northern Ireland?", ["Belfast", "Dublin", "Londonderry", "Armagh"], 0, "Belfast is the capital.", "Belfast capital!"],
  [262, c2, "Longest distance on UK mainland?", ["Dover-York", "London-Edinburgh", "Land's End-John O'Groats", "Cardiff-Belfast"], 2, "Land's End to John O'Groats.", "End to Groats!"],
  [263, c2, "Central War Memorial in Whitehall?", ["Cenotaph", "White Tower", "Abbey", "Crescent"], 0, "The Cenotaph.", "Cenotaph for the fallen!"],
  [264, c2, "Longest river in the UK?", ["Thames", "Severn", "Clyde", "Trent"], 1, "The River Severn.", "Severn is longest!"],

  // --- EXAM 12 ---
  [265, c2, "Which is a Crown Dependency but NOT part of UK?", ["Shetland", "Isle of Wight", "Isle of Man", "Anglesey"], 2, "Isle of Man and Channel Islands.", "Isle of Man is a dependency!"],
  [266, c4, "Is the BBC controlled by the government?", ["Yes", "No", "", ""], 1, "No, it is independent.", "BBC is independent!"],
  [267, c5, "How many members does Northern Ireland Assembly have?", ["12", "60", "90", "108"], 2, "It has 90 MLAs.", "90 in NI Assembly!"],
  [268, c3, "Who was in charge of British fleet at Trafalgar?", ["Cromwell", "Wellington", "Bruce", "Admiral Nelson"], 3, "Admiral Nelson was in charge.", "Nelson at sea!"],
  [269, c3, "Inscribed on first Iron Age coins?", ["Names of kings", "Gods", "Trees", "Animals"], 0, "Names of Iron Age kings.", "Iron Kings on coins!"],
  [270, c4, "Major sports event in UK in 2012?", ["World Cup", "Rugby", "Olympic games", "Eurocup"], 2, "The 2012 Olympics.", "2012 Olympics!"],
  [271, c3, "Charles I 'Divine Right' so he tried:", ["Rule without Parliament", "Rule with approval", "Raise money", "Restore Catholicism"], 0, "To rule without Parliament.", "Ignored Parliament!"],
  [272, c2, "What is the Union Jack?", ["Commonwealth flag", "Flag of the United Kingdom", "Shield", "Trade union"], 1, "It is the UK flag.", "Union Jack is UK flag!"],
  [273, c3, "Greatest Briton of all time in 2002?", ["Mo Farah", "Nelson", "Winston Churchill", "Attlee"], 2, "Winston Churchill.", "Churchill the Greatest!"],
  [274, c4, "Women in workforce today?", ["Half", "Quarter", "", ""], 0, "Women make up about half.", "Half the workforce!"],
  [275, c3, "Who invented World Wide Web in 1989?", ["Turing", "Tim Berners-Lee", "Whittle", "Watson-Watt"], 1, "Sir Tim Berners-Lee.", "Tim spun the Web!"],
  [276, c3, "Scottish scientist discovered penicillin 1928?", ["Alexander Fleming", "Rutherford", "Florey", "Crick"], 0, "Sir Alexander Fleming.", "Fleming stopped phlegm!"],
  [277, c3, "Inventor of hovercraft 1950s?", ["Whittle", "Christopher Cockerell", "Goodfellow", "Mansfield"], 1, "Sir Christopher Cockerell.", "Cockerell hovers!"],
  [278, c3, "Inventor of ATM 1960s?", ["Baird", "James Goodfellow", "Mansfield", "Wilmot"], 1, "James Goodfellow.", "Goodfellow gave cash!"],
  [279, c3, "Co-discovered DNA structure?", ["Rutherford", "Francis Crick and James Watson", "Fleming", "Wilmot"], 1, "Crick and Watson.", "Crick and Watson DNA!"],
  [280, c3, "Victorian engineer built Great Western Railway?", ["Stephenson", "Isambard Kingdom Brunel", "Arkwright", "Watt"], 1, "Isambard Kingdom Brunel.", "Brunel built rails!"],
  [281, c3, "Cloned Dolly the sheep?", ["Mansfield", "Ian Wilmot", "Edwards", "Crick"], 1, "Sir Ian Wilmot.", "Wilmot cloned wool!"],
  [282, c3, "Nobel for MRI scanner?", ["Edwards", "Peter Mansfield", "Whittle", "Cockerell"], 1, "Sir Peter Mansfield.", "Mansfield mapped MRI!"],
  [283, c4, "1960s fashion designer miniskirt?", ["McQueen", "Mary Quant", "Westwood", "McCartney"], 1, "Mary Quant.", "Quant's quantity of miniskirts!"],
  [284, c4, "Home of golf?", ["Edinburgh", "St Andrews", "Inverness", "Glasgow"], 1, "St Andrews is the home of golf.", "St Andrews golf!"],
  [285, c4, "Players on a Rugby Union team?", ["11", "13", "15", "18"], 2, "Rugby Union has 15 players.", "Union is 15!"],
  [286, c4, "National stadium of English Rugby?", ["Wembley", "Twickenham", "Murrayfield", "Hampden"], 1, "Twickenham.", "Twickenham rugby!"],
  [287, c4, "Scottish rugby stadium?", ["Hampden", "Murrayfield", "Celtic", "Ibrox"], 1, "Murrayfield.", "Murrayfield for Scotland!"],
  [288, c4, "Pen name George Eliot?", ["Mary Ann Evans", "Brontë", "Shelley", "Gaskell"], 0, "Mary Ann Evans.", "Evans was Eliot!"],

  // --- EXAM 13 ---
  [289, c4, "When is St George's day?", ["17th March", "30th November", "1st March", "23rd April"], 3, "St George is 23 April.", "George slays 23rd April!"],
  [290, c2, "Largest National Park in England?", ["Snowdonia", "Loch Lomond", "Causeway", "Lake District"], 3, "The Lake District.", "Lake District is biggest!"],
  [291, c3, "Boudicca fought against which invaders?", ["Normans", "Vikings", "Anglo-Saxons", "Romans"], 3, "She fought the Romans.", "Boudicca fought Rome!"],
  [292, c4, "Poem about pilgrimage?", ["Canterbury Tales", "Stage", "Midsummer", "Expectations"], 0, "The Canterbury Tales.", "Chaucer's Canterbury!"],
  [293, c4, "Shopping in the UK?", ["Most open 7 days", "All close Sunday", "", ""], 0, "Most shops are open 7 days a week.", "Shop 7 days!"],
  [294, c3, "Country sent fleet to England in 1588?", ["France", "Germany", "Spain", "Italy"], 2, "Spain sent the Armada.", "Spanish Armada 1588!"],
  [295, c4, "National Horseracing Museum located?", ["Edinburgh", "Newmarket, Suffolk", "St Andrews", "Aintree"], 1, "It is in Newmarket.", "Newmarket for horses!"],
  [296, c2, "Castle located in Scotland?", ["Crathes Castle", "Caernarfon", "Bodiam", "Powis"], 0, "Crathes Castle.", "Crathes in Scotland!"],
  [297, c4, "Art Deco ceramic designer?", ["McQueen", "Chippendale", "Clarice Cliff", "Quant"], 2, "Clarice Cliff.", "Clarice's Ceramics!"],
  [298, c4, "Wrote 'Far from the Madding Crowd'?", ["Thomas Hardy", "Dickens", "Greene", "Waugh"], 0, "Thomas Hardy.", "Hardy rural reality!"],
  [299, c4, "Wrote 'Treasure Island'?", ["Robert Louis Stevenson", "Conan Doyle", "Burns", "Scott"], 0, "Robert Louis Stevenson.", "Stevenson's Island!"],
  [300, c4, "Wrote 'The Jungle Book'?", ["Rudyard Kipling", "Wordsworth", "Thomas", "Milton"], 0, "Rudyard Kipling.", "Kipling the jungle!"],
  [301, c4, "Satirical author of 'Scoop'?", ["Evelyn Waugh", "Greene", "Amis", "Eliot"], 0, "Evelyn Waugh.", "Waugh makes you laugh!"],
  [302, c4, "Author of 'Lucky Jim'?", ["Kingsley Amis", "Waugh", "Greene", "Forster"], 0, "Kingsley Amis.", "Amis-ed by Jim!"],
  [303, c4, "Author of 'Brighton Rock'?", ["Graham Greene", "Waugh", "Amis", "Hardy"], 0, "Graham Greene.", "Greene's rock!"],
  [304, c4, "Sculptor of massive abstract bronze?", ["Henry Moore", "Hepworth", "Chippendale", "Constable"], 0, "Henry Moore.", "Moore massive bronze!"],
  [305, c4, "Pioneering female abstract sculptor?", ["Barbara Hepworth", "Cliff", "Quant", "Lynn"], 0, "Barbara Hepworth.", "Hepworth Yorkshire stones!"],
  [306, c4, "Painter of 'The Hay Wain'?", ["John Constable", "Turner", "Hogarth", "Rossetti"], 0, "John Constable.", "Constable Country!"],
  [307, c4, "Painter of light?", ["J.M.W. Turner", "Constable", "Gainsborough", "Rossetti"], 0, "J.M.W. Turner.", "Turner's light!"],
  [308, c4, "18th-century portrait painter?", ["Thomas Gainsborough", "Engraver", "Sculptor", "Caricature"], 0, "Thomas Gainsborough.", "Gainsborough portraits!"],
  [309, c4, "Painter of 'A Rake's Progress'?", ["William Hogarth", "Gainsborough", "Turner", "Constable"], 0, "William Hogarth.", "Hogarth's progress!"],
  [310, c4, "Co-founded Pre-Raphaelites?", ["Dante Gabriel Rossetti", "Hogarth", "Constable", "Gainsborough"], 0, "Dante Gabriel Rossetti.", "Rossetti pre-Raphael!"],
  [311, c4, "Comic opera 'The Mikado'?", ["Gilbert and Sullivan", "Webber", "Purcell", "Elgar"], 0, "Gilbert and Sullivan.", "G&S comic opera!"],
  [312, c4, "Composer of 'Cats'?", ["Andrew Lloyd Webber", "Britten", "Elgar", "Purcell"], 0, "Andrew Lloyd Webber.", "Webber's Cats!"],

  // --- EXAM 14 ---
  [313, c4, "When is St Patrick's day celebrated?", ["23 Apr", "30 Nov", "1 Apr", "17th March"], 3, "St Patrick is 17 March.", "Patrick marches 17th!"],
  [314, c5, "How are members of NI Parliament elected?", ["Proportional representation", "Ranked", "First past post", "Runoff"], 0, "By proportional representation (STV).", "PR in NI!"],
  [315, c3, "Who was the first British Prime Minister?", ["Churchill", "Wilmington", "Pelham", "Sir Robert Walpole"], 3, "Sir Robert Walpole.", "Walpole the first!"],
  [316, c4, "Which actress has not won an Oscar?", ["Swinton", "Emily Watson", "Dench", "Winslet"], 1, "Emily Watson has not.", "Watson waiting!"],
  [317, c3, "Why were canals built during the Industrial Revolution?", ["Link factories to towns/ports", "Space for ships", "Water mills", "Increase water"], 0, "To transport goods.", "Canals for transport!"],
  [318, c5, "Are civil servants appointed by the government?", ["Yes", "No", "", ""], 1, "No, chosen on merit/politically neutral.", "Merit not politics!"],
  [319, c3, "Country helped Britain develop Concorde?", ["Germany", "Norway", "Italy", "France"], 3, "France co-developed it.", "French connection Concorde!"],
  [320, c3, "Invention led to Industrial Revolution?", ["MRI", "Steam power", "Radar", "Hovercraft"], 1, "Steam power.", "Steam powered factories!"],
  [321, c3, "Tribal leader who fought Romans?", ["Columba", "Claudius", "Hadrian", "Boudicca"], 3, "Boudicca.", "Boudicca fought Rome!"],
  [322, c4, "Baroque composer at Westminster Abbey?", ["Henry Purcell", "Painter", "Architect", "PM"], 0, "Henry Purcell.", "Purcell baroque!"],
  [323, c4, "Composer of 'Pomp and Circumstance'?", ["Sir Edward Elgar", "Vaughan Williams", "Britten", "Purcell"], 0, "Sir Edward Elgar.", "Elgar Pomp!"],
  [324, c4, "Revived English folk classical music?", ["Ralph Vaughan Williams", "Elgar", "Britten", "Purcell"], 0, "Ralph Vaughan Williams.", "Vaughan Williams folk!"],
  [325, c4, "Composer of 'Peter Grimes'?", ["Benjamin Britten", "Elgar", "Vaughan Williams", "Purcell"], 0, "Benjamin Britten.", "Britten opera!"],
  [326, c4, "WWII Forces' Sweetheart?", ["Dame Vera Lynn", "Quant", "Cliff", "Thompson"], 0, "Dame Vera Lynn.", "Vera Lynn WWII!"],
  [327, c3, "Co-discovered insulin?", ["John Macleod", "Fleming", "Harvey", "Crick"], 0, "John Macleod.", "Macleod insulin!"],
  [328, c3, "Built Jodrell Bank telescope?", ["Sir Bernard Lovell", "Mansfield", "Whittle", "Berners-Lee"], 0, "Sir Bernard Lovell.", "Lovell telescope!"],
  [329, c3, "Pioneered IVF test-tube baby?", ["Edwards & Steptoe", "Wilmot", "Fleming", "Harvey"], 0, "Robert Edwards & Patrick Steptoe.", "Edwards Steptoe IVF!"],
  [330, c4, "Five consecutive Olympic rowing golds?", ["Sir Steve Redgrave", "Bannister", "Wiggins", "Hoy"], 0, "Sir Steve Redgrave.", "Redgrave rowed 5!"],
  [331, c4, "11 gold medals wheelchair racing?", ["Tanni Grey-Thompson", "Ennis-Hill", "Holmes", "MacArthur"], 0, "Baroness Tanni Grey-Thompson.", "Tanni on wheels!"],
  [332, c4, "Sailed solo non-stop in 71 days?", ["Dame Ellen MacArthur", "Holmes", "Grey-Thompson", "Ennis-Hill"], 0, "Dame Ellen MacArthur.", "MacArthur solo sail!"],
  [333, c3, "Architect who designed Cenotaph?", ["Wren", "Sir Edwin Lutyens", "Adam", "Brown"], 1, "Sir Edwin Lutyens.", "Lutyens Cenotaph!"],
  [334, c3, "Nickname for Lancelot Brown?", ["Capability", "Wood", "Cliff", "Adam"], 0, "Capability Brown.", "Capability landscapes!"],
  [335, c3, "Master wood carver Georgian furniture?", ["Thomas Chippendale", "Adam", "Cliff", "Caxton"], 0, "Thomas Chippendale.", "Chippendale chairs!"],
  [336, c3, "Carding and spinning machines?", ["Richard Arkwright", "Stephenson", "Brunel", "Watt"], 0, "Richard Arkwright.", "Arkwright spun textile!"],

  // --- EXAM 15 ---
  [337, c3, "Languages used in Middle Ages?", ["Welsh", "Gaelic", "Norman French & Anglo-Saxon", "Celtic"], 2, "Norman French (nobles) and Anglo-Saxon (peasants).", "French nobles, Saxon peasants!"],
  [338, c3, "1776 colonies declared independence?", ["North African", "Asian", "North American", "South African"], 2, "13 North American colonies.", "America 1776!"],
  [339, c3, "When was England ruled by a republic?", ["Elizabeth died", "When Charles I was executed", "Carta Magna", "Harold died"], 1, "After Charles I was executed.", "No King after Charles!"],
  [340, c4, "Highest-grossing film franchise UK?", ["Harry Potter", "Spider-man", "Lord of Rings", "Indiana Jones"], 0, "Harry Potter (and James Bond).", "Potter prints money!"],
  [341, c5, "Minimum age to drive motorcycle?", ["16", "17 years old", "18", "21"], 1, "You must be 17.", "17 for motorcycle!"],
  [342, c5, "Peers in Lords are elected by people.", ["True", "False", "", ""], 1, "False, they are appointed.", "Peers are appointed!"],
  [343, c3, "Emancipation Act abolished slavery when?", ["1835", "1823", "1807", "1833"], 3, "Slavery abolished in 1833.", "33 freed slaves!"],
  [344, c5, "Responsible for crime, policing, immigration?", ["Chancellor", "Foreign Sec", "Speaker", "Home Secretary"], 3, "The Home Secretary.", "Home Sec stops crime!"],
  [345, c4, "Wallace and Gromit genre?", ["Soap", "Silent", "Animated", "Action"], 2, "They are animated films.", "Animated clay!"],
  [346, c5, "Violent to partner prosecuted?", ["True", "False", "", ""], 0, "True, domestic violence is illegal.", "Violence is illegal!"],
  [347, c3, "Founder of modern nursing?", ["Florence Nightingale", "Pankhurst", "Seacole", "Fry"], 0, "Florence Nightingale.", "Nightingale nurse!"],
  [348, c1, "English level for settlement?", ["Level 1", "Level 2", "Level 3", "Level 4"], 2, "ESOL Entry Level 3 (B1).", "Level 3 for FREE!"],
  [349, c5, "Max small claims in England/Wales?", ["£1k", "£3k", "£5k", "£10,000"], 3, "£10,000 in England/Wales.", "Ten grand E&W!"],
  [350, c5, "Breach of Forced Marriage Order penalty?", ["6 months", "2 years", "5 years", "10 years"], 1, "Up to 2 years in prison.", "2 years for forcing 2!"],
  [351, c4, "Fine for no TV licence?", ["£100", "£500", "£1,000", "£5,000"], 2, "Up to £1,000.", "Grand for no TV!"],
  [352, c5, "When is electoral register updated?", ["Jan/Feb", "Apr/May", "Sept/Oct", "Nov/Dec"], 2, "September or October.", "Autumn update!"],
  [353, c5, "Age to be school governor?", ["16", "18 or over", "21", "25"], 1, "Must be 18 or over.", "Adult at 18!"],
  [354, c5, "Age for National Citizen Service?", ["14/15", "16 and 17", "18/19", "21/22"], 1, "16 and 17 year olds.", "Sweet 16 & 17!"],
  [355, c5, "Department collecting income tax?", ["DWP", "HMRC", "Home Office", "Treasury"], 1, "HM Revenue & Customs (HMRC).", "HMRC collects!"],
  [356, c5, "Newly qualified driver NI letter?", ["L", "P", "R", "N"], 2, "An 'R' plate (restricted).", "R for Restricted NI!"],
  [357, c4, "Percentage Christian in 2009 Survey?", ["40%", "50%", "70%", "90%"], 2, "70% identified as Christian.", "70% Christian!"],
  [358, c5, "Core value of civil service?", ["Profit", "Bias", "Creativity", "Impartiality"], 3, "Impartiality is a core value.", "Impartial servants!"],
  [359, c5, "Who CANNOT stand as MP?", ["Teachers", "Armed forces", "Doctors", "Self-employed"], 1, "Armed forces, civil servants, some criminals.", "Soldiers don't stand!"],
  [360, c1, "Test language other than English?", ["Welsh/Gaelic", "Irish/Cornish", "French/German", "Spanish/Italian"], 0, "Welsh or Scottish Gaelic.", "Gaelic/Welsh treasures!"],

  // --- EXAM 16 ---
  [361, c5, "When was UN set up?", ["After WWI", "After WWII", "Before WWI", "Before WWII"], 1, "After the Second World War.", "UN after WWII!"],
  [362, c2, "Where is Giant's Causeway?", ["Scotland", "England", "Wales", "Northern Ireland"], 3, "Northern Ireland.", "Giants in NI!"],
  [363, c3, "What happened to Mary Queen of Scots?", ["Married", "Sent to France", "Executed", "Sent to Scotland"], 2, "She was executed by Elizabeth I.", "Mary lost her head!"],
  [364, c3, "Tribe after Romans left AD 410?", ["Gepids", "Jutes", "Frisians", "Burgundians"], 1, "Jutes (Angles & Saxons).", "Jutes joined in!"],
  [365, c5, "What is the Commonwealth?", ["Military", "Association supporting democracy", "", ""], 1, "Association of countries supporting each other.", "Wealth of common goals!"],
  [366, c3, "Movement against Pope by Henry VIII?", ["Inquisition", "Holy Wars", "The Reformation", "Enlightenment"], 2, "The Reformation.", "Reforming the church!"],
  [367, c4, "What did Isaac Newton discover?", ["Gravity", "Penicillin", "Insulin", "Lightbulb"], 0, "He discovered gravity.", "Newton's gravity!"],
  [368, c4, "Nick Park movies?", ["Action", "Animated", "Thrillers", "Horror"], 1, "Animated films (Wallace & Gromit).", "Animated clay!"],
  [369, c1, "Citizenship pledge includes?", ["Loyalty/Rights/Freedoms", "Vote local", "Pay taxes", "Military"], 0, "Loyalty, rights, and freedoms.", "Loyalty & Rights!"],
  [370, c4, "Muslim population 2009 survey?", ["2%", "4%", "10%", "15%"], 1, "4% identified as Muslim.", "4% Islamic faith!"],
  [371, c4, "Why ageing population?", ["Low birth", "Improved living/health", "Emigration", "Employment"], 1, "Improved living standards and health care.", "Better health, longer life!"],
  [372, c5, "Scottish jury third verdict?", ["Undecided", "Not proven", "Mistrial", "Suspended"], 1, "A third verdict of 'not proven'.", "Not proven in Scotland!"],
  [373, c5, "Most serious criminal cases Scotland?", ["Sheriff", "High Court", "Crown", "Peace"], 1, "High Court handles them.", "High crimes High Court!"],
  [374, c5, "How is jury selected?", ["Random from electoral register", "Police", "Volunteers", "Phonebook"], 0, "Randomly from the electoral register.", "Random from register!"],
  [375, c5, "System for young offenders Scotland?", ["Youth Court", "Children's Hearings", "Conferencing", "Sheriff"], 1, "Children's Hearings System.", "Scotland hears children!"],
  [376, c5, "System for young offenders NI?", ["Youth Court", "Hearings", "Youth conferencing", "High"], 2, "Youth conferencing.", "NI youth conference!"],
  [377, c5, "Charity protecting children?", ["Age UK", "PDSA", "NSPCC", "Shelter"], 2, "NSPCC protects children.", "Never Suffer Cruelty!"],
  [378, c5, "Charity for sick animals?", ["Homeless", "Sick animals (PDSA)", "Older", "Environment"], 1, "PDSA helps sick animals.", "Pets Deserve Attention!"],
  [379, c5, "Living organ donation?", ["Blood", "Kidney", "Marrow", "Liver"], 1, "Living people can donate a kidney.", "Share a kidney!"],
  [380, c5, "Volunteer for police?", ["Support", "Special constable", "Army", "Magistrate"], 1, "Become a special constable.", "Special volunteers!"],
  [381, c5, "PTA in schools?", ["Parent-Teacher Association", "Primary", "Toddler", "Public"], 0, "Parent-Teacher Association.", "Parents & Teachers!"],
  [382, c4, "Age for free TV licence (w/ credit)?", ["60", "65", "70", "75"], 3, "Over 75.", "75 for free TV!"],
  [383, c4, "Blind TV licence discount?", ["25%", "50%", "75%", "100%"], 1, "50% discount.", "Half off for blind!"],
  [384, c5, "MOT test required when?", ["1 yr", "3 yrs old", "5 yrs", "10k miles"], 1, "When vehicle is over 3 years old.", "3 years on the road!"],

  // --- EXAM 17 ---
  [385, c5, "NOT a constitutional institution?", ["Parliament", "Cabinet", "Armed forces", "Police"], 2, "Armed forces are not constitutional institutions.", "Army fights, doesn't govern!"],
  [386, c3, "Famine in Ireland caused by?", ["Corn", "Potato", "Wheat", "Oats"], 1, "The potato crop failed.", "Potato famine!"],
  [387, c5, "Group of senior opposition MPs?", ["Shadow Cabinet", "Lobby", "Civil servants", "Peers"], 0, "They form the Shadow Cabinet.", "Shadows watch Cabinet!"],
  [388, c5, "Two responsibilities of MPs?", ["Protect life", "Represent everyone & scrutinise govt", "", ""], 1, "Represent constituents and challenge government.", "Represent & Scrutinise!"],
  [389, c3, "Who was asked to invade in 1688?", ["Medina", "Napoleon", "Philip II", "William of Orange"], 3, "William of Orange was invited.", "Orange invasion!"],
  [390, c3, "Defeated at Battle of Boyne?", ["James I", "James II", "Richard I", "Richard II"], 1, "James II was defeated.", "James II lost Boyne!"],
  [391, c3, "Factories Act 1847?", ["10 hrs everybody", "12 hrs women/kids", "12 hrs men", "10 hrs women/kids"], 3, "Limited women/children to 10 hours.", "10 hours for kids!"],
  [392, c5, "Name of MPs from opposition?", ["Roundheads", "Cavaliers", "Shadow Cabinet", "Quakers"], 2, "Shadow Cabinet challenges the government.", "Shadows challenge!"],
  [393, c5, "Scottish Parliament can legislate on?", ["Education", "Immigration", "Security", "Defence"], 0, "Education is a devolved matter.", "Scotland runs schools!"],
  [394, c5, "Legal drinking age in pub?", ["16", "18", "21", "25"], 1, "Must be 18 to buy alcohol.", "18 for a pint!"],
  [395, c5, "Age to drink wine with meal (w/ adult)?", ["14", "16", "18", "21"], 1, "16 years old with an adult.", "Sweet 16 sip!"],
  [396, c5, "Police complaints body E&W?", ["Ombudsman", "Commissioner", "IOPC (formerly IPCC)", "Home Office"], 2, "Independent Office for Police Conduct.", "Independent conduct!"],
  [397, c5, "Sets local police priorities E&W?", ["PM", "Police and Crime Commissioners", "Home Sec", "Mayor"], 1, "PCCs set priorities and budgets.", "PCCs Pick Cash!"],
  [398, c5, "National Insurance number used for?", ["Healthcare", "Ensure tax/NI recorded", "Passport", "Vote"], 1, "Records tax and NI contributions.", "Name & Income tracking!"],
  [399, c5, "When are NI numbers sent?", ["Before 16th birthday", "Before 18th", "First job", "Uni"], 0, "Sent just before 16th birthday.", "Before 16 NI!"],
  [400, c1, "Equal rights in the UK?", ["Only men", "Property owners", "Men and women", "Citizens"], 2, "Men and women have equal rights.", "Equal society!"],
  [401, c2, "Countries making up Great Britain?", ["E, S, W", "E, S, W, NI", "E, W", "E, S"], 0, "England, Scotland, and Wales.", "GB is 3!"],
  [402, c2, "St George's Day?", ["1 Mar", "17 Mar", "23 Apr", "30 Nov"], 2, "St George is 23 April.", "George slays 23rd!"],
  [403, c2, "Longest distance UK mainland?", ["London-Edinburgh", "John O'Groats to Land's End", "Cardiff-Belfast", "Manchester-South"], 1, "John O'Groats to Land's End.", "End to Groats!"],
  [404, c2, "Giant Ferris wheel in London?", ["Eden Project", "London Eye", "Tower", "Big Ben"], 1, "The London Eye on the Thames.", "Eye on the Thames!"],
  [405, c4, "What is Shrove Tuesday?", ["Ash Wednesday", "Pancake Day", "Easter", "Good Friday"], 1, "Also known as Pancake Day.", "Pancakes on Tuesday!"],
  [406, c4, "Sikh festival 14 April?", ["Diwali", "Vaisakhi", "Hannukah", "Eid"], 1, "Vaisakhi celebrates the Khalsa.", "Vaisakhi for Khalsa!"],
  [407, c4, "Scottish dish stuffed sheep stomach?", ["Welsh cakes", "Haggis", "Ulster fry", "Beef"], 1, "Haggis is a traditional Scottish dish.", "Haggis for Highlands!"],
  [408, c4, "Awards equivalent to Oscars?", ["BAFTAs", "Olivier", "Mercury", "Turner"], 0, "BAFTAs are the British Oscars.", "BAFTA for Best Actors!"]
];
